version: "2.1"

services:
  spark-master:
    image: "dpavlov/spark:latest"
    hostname: spark-master
    container_name: spark-master
    networks:
      - host
    environment:
      - MASTER=0.0.0.0
    expose:
      - 4040
      - 7077
      - 8080
    ports:
      - "4040:4040"
      - "8080:8080"
      - "7077:7077"
    command: ["/usr/share/master_ip.sh"]

  spark-slave:
    image: "dpavlov/spark:latest"
    hostname: spark-slave
    container_name: spark-slave
    networks:
      - host
    environment:
      - MASTER=172.31.19.167
    expose:
      - 4040
      - 8080
    ports:
      - "4041:4040"
      - "8081:8080"
    links:
      - spark-master
    depends_on:
      - spark-master
    command: ["/usr/share/slaves_ip.sh"]

networks:
  host: