// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookRoomInfo.proto

package com.jactravel.monitoring;

public interface BookRoomInfoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 adults = 1;
  /**
   * <code>optional int32 adults = 1;</code>
   */
  boolean hasAdults();
  /**
   * <code>optional int32 adults = 1;</code>
   */
  int getAdults();

  // optional int32 children = 2;
  /**
   * <code>optional int32 children = 2;</code>
   */
  boolean hasChildren();
  /**
   * <code>optional int32 children = 2;</code>
   */
  int getChildren();

  // repeated int32 childAges = 3;
  /**
   * <code>repeated int32 childAges = 3;</code>
   */
  java.util.List<java.lang.Integer> getChildAgesList();
  /**
   * <code>repeated int32 childAges = 3;</code>
   */
  int getChildAgesCount();
  /**
   * <code>repeated int32 childAges = 3;</code>
   */
  int getChildAges(int index);

  // optional int32 mealBasisID = 4;
  /**
   * <code>optional int32 mealBasisID = 4;</code>
   */
  boolean hasMealBasisID();
  /**
   * <code>optional int32 mealBasisID = 4;</code>
   */
  int getMealBasisID();

  // optional string bookingToken = 5;
  /**
   * <code>optional string bookingToken = 5;</code>
   */
  boolean hasBookingToken();
  /**
   * <code>optional string bookingToken = 5;</code>
   */
  java.lang.String getBookingToken();
  /**
   * <code>optional string bookingToken = 5;</code>
   */
  com.google.protobuf.ByteString
      getBookingTokenBytes();

  // optional int32 propertyRoomTypeID = 6;
  /**
   * <code>optional int32 propertyRoomTypeID = 6;</code>
   */
  boolean hasPropertyRoomTypeID();
  /**
   * <code>optional int32 propertyRoomTypeID = 6;</code>
   */
  int getPropertyRoomTypeID();

  // optional string priceDiff = 7;
  /**
   * <code>optional string priceDiff = 7;</code>
   */
  boolean hasPriceDiff();
  /**
   * <code>optional string priceDiff = 7;</code>
   */
  java.lang.String getPriceDiff();
  /**
   * <code>optional string priceDiff = 7;</code>
   */
  com.google.protobuf.ByteString
      getPriceDiffBytes();
}
