// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookRequest.proto

package com.jactravel.monitoring;

/**
 * Protobuf type {@code Jactravel.Monitoring.BookRequest}
 */
public  final class BookRequest extends
    com.google.protobuf.GeneratedMessage
    implements BookRequestOrBuilder {
  // Use BookRequest.newBuilder() to construct.
  private BookRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private BookRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final BookRequest defaultInstance;
  public static BookRequest getDefaultInstance() {
    return defaultInstance;
  }

  public BookRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private BookRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            queryUUID_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            searchQueryUUID_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            preBookQueryUUID_ = input.readBytes();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();
            com.jactravel.monitoring.PlatformType value = com.jactravel.monitoring.PlatformType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(4, rawValue);
            } else {
              bitField0_ |= 0x00000008;
              searchProcessor_ = value;
            }
            break;
          }
          case 42: {
            bitField0_ |= 0x00000010;
            host_ = input.readBytes();
            break;
          }
          case 50: {
            bitField0_ |= 0x00000020;
            startUtcTimestamp_ = input.readBytes();
            break;
          }
          case 58: {
            bitField0_ |= 0x00000040;
            endUtcTimestamp_ = input.readBytes();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000080;
            tradeID_ = input.readInt32();
            break;
          }
          case 72: {
            bitField0_ |= 0x00000100;
            brandID_ = input.readInt32();
            break;
          }
          case 80: {
            bitField0_ |= 0x00000200;
            salesChannelID_ = input.readInt32();
            break;
          }
          case 88: {
            bitField0_ |= 0x00000400;
            propertyID_ = input.readInt32();
            break;
          }
          case 98: {
            bitField0_ |= 0x00000800;
            arrivalDate_ = input.readBytes();
            break;
          }
          case 104: {
            bitField0_ |= 0x00001000;
            duration_ = input.readInt32();
            break;
          }
          case 114: {
            if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
              rooms_ = new java.util.ArrayList<com.jactravel.monitoring.BookRoomInfo>();
              mutable_bitField0_ |= 0x00002000;
            }
            rooms_.add(input.readMessage(com.jactravel.monitoring.BookRoomInfo.PARSER, extensionRegistry));
            break;
          }
          case 120: {
            bitField0_ |= 0x00002000;
            currencyID_ = input.readInt32();
            break;
          }
          case 130: {
            bitField0_ |= 0x00004000;
            preBookingToken_ = input.readBytes();
            break;
          }
          case 138: {
            bitField0_ |= 0x00008000;
            errorMessage_ = input.readBytes();
            break;
          }
          case 146: {
            bitField0_ |= 0x00010000;
            errorStackTrace_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
        rooms_ = java.util.Collections.unmodifiableList(rooms_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jactravel.monitoring.BookRequestProto.internal_static_Jactravel_Monitoring_BookRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jactravel.monitoring.BookRequestProto.internal_static_Jactravel_Monitoring_BookRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jactravel.monitoring.BookRequest.class, com.jactravel.monitoring.BookRequest.Builder.class);
  }

  public static com.google.protobuf.Parser<BookRequest> PARSER =
      new com.google.protobuf.AbstractParser<BookRequest>() {
    public BookRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BookRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<BookRequest> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional string queryUUID = 1;
  public static final int QUERYUUID_FIELD_NUMBER = 1;
  private java.lang.Object queryUUID_;
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  public boolean hasQueryUUID() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  public java.lang.String getQueryUUID() {
    java.lang.Object ref = queryUUID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        queryUUID_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getQueryUUIDBytes() {
    java.lang.Object ref = queryUUID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      queryUUID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string searchQueryUUID = 2;
  public static final int SEARCHQUERYUUID_FIELD_NUMBER = 2;
  private java.lang.Object searchQueryUUID_;
  /**
   * <code>optional string searchQueryUUID = 2;</code>
   */
  public boolean hasSearchQueryUUID() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string searchQueryUUID = 2;</code>
   */
  public java.lang.String getSearchQueryUUID() {
    java.lang.Object ref = searchQueryUUID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        searchQueryUUID_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string searchQueryUUID = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSearchQueryUUIDBytes() {
    java.lang.Object ref = searchQueryUUID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      searchQueryUUID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string preBookQueryUUID = 3;
  public static final int PREBOOKQUERYUUID_FIELD_NUMBER = 3;
  private java.lang.Object preBookQueryUUID_;
  /**
   * <code>optional string preBookQueryUUID = 3;</code>
   */
  public boolean hasPreBookQueryUUID() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string preBookQueryUUID = 3;</code>
   */
  public java.lang.String getPreBookQueryUUID() {
    java.lang.Object ref = preBookQueryUUID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        preBookQueryUUID_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string preBookQueryUUID = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPreBookQueryUUIDBytes() {
    java.lang.Object ref = preBookQueryUUID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      preBookQueryUUID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional .Jactravel.Monitoring.PlatformType searchProcessor = 4;
  public static final int SEARCHPROCESSOR_FIELD_NUMBER = 4;
  private com.jactravel.monitoring.PlatformType searchProcessor_;
  /**
   * <code>optional .Jactravel.Monitoring.PlatformType searchProcessor = 4;</code>
   */
  public boolean hasSearchProcessor() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .Jactravel.Monitoring.PlatformType searchProcessor = 4;</code>
   */
  public com.jactravel.monitoring.PlatformType getSearchProcessor() {
    return searchProcessor_;
  }

  // optional string host = 5;
  public static final int HOST_FIELD_NUMBER = 5;
  private java.lang.Object host_;
  /**
   * <code>optional string host = 5;</code>
   */
  public boolean hasHost() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string host = 5;</code>
   */
  public java.lang.String getHost() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        host_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string host = 5;</code>
   */
  public com.google.protobuf.ByteString
      getHostBytes() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      host_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string startUtcTimestamp = 6;
  public static final int STARTUTCTIMESTAMP_FIELD_NUMBER = 6;
  private java.lang.Object startUtcTimestamp_;
  /**
   * <code>optional string startUtcTimestamp = 6;</code>
   */
  public boolean hasStartUtcTimestamp() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string startUtcTimestamp = 6;</code>
   */
  public java.lang.String getStartUtcTimestamp() {
    java.lang.Object ref = startUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        startUtcTimestamp_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string startUtcTimestamp = 6;</code>
   */
  public com.google.protobuf.ByteString
      getStartUtcTimestampBytes() {
    java.lang.Object ref = startUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startUtcTimestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string endUtcTimestamp = 7;
  public static final int ENDUTCTIMESTAMP_FIELD_NUMBER = 7;
  private java.lang.Object endUtcTimestamp_;
  /**
   * <code>optional string endUtcTimestamp = 7;</code>
   */
  public boolean hasEndUtcTimestamp() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional string endUtcTimestamp = 7;</code>
   */
  public java.lang.String getEndUtcTimestamp() {
    java.lang.Object ref = endUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        endUtcTimestamp_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string endUtcTimestamp = 7;</code>
   */
  public com.google.protobuf.ByteString
      getEndUtcTimestampBytes() {
    java.lang.Object ref = endUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endUtcTimestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int32 tradeID = 8;
  public static final int TRADEID_FIELD_NUMBER = 8;
  private int tradeID_;
  /**
   * <code>optional int32 tradeID = 8;</code>
   */
  public boolean hasTradeID() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional int32 tradeID = 8;</code>
   */
  public int getTradeID() {
    return tradeID_;
  }

  // optional int32 brandID = 9;
  public static final int BRANDID_FIELD_NUMBER = 9;
  private int brandID_;
  /**
   * <code>optional int32 brandID = 9;</code>
   */
  public boolean hasBrandID() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional int32 brandID = 9;</code>
   */
  public int getBrandID() {
    return brandID_;
  }

  // optional int32 salesChannelID = 10;
  public static final int SALESCHANNELID_FIELD_NUMBER = 10;
  private int salesChannelID_;
  /**
   * <code>optional int32 salesChannelID = 10;</code>
   */
  public boolean hasSalesChannelID() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional int32 salesChannelID = 10;</code>
   */
  public int getSalesChannelID() {
    return salesChannelID_;
  }

  // optional int32 propertyID = 11;
  public static final int PROPERTYID_FIELD_NUMBER = 11;
  private int propertyID_;
  /**
   * <code>optional int32 propertyID = 11;</code>
   */
  public boolean hasPropertyID() {
    return ((bitField0_ & 0x00000400) == 0x00000400);
  }
  /**
   * <code>optional int32 propertyID = 11;</code>
   */
  public int getPropertyID() {
    return propertyID_;
  }

  // optional string arrivalDate = 12;
  public static final int ARRIVALDATE_FIELD_NUMBER = 12;
  private java.lang.Object arrivalDate_;
  /**
   * <code>optional string arrivalDate = 12;</code>
   */
  public boolean hasArrivalDate() {
    return ((bitField0_ & 0x00000800) == 0x00000800);
  }
  /**
   * <code>optional string arrivalDate = 12;</code>
   */
  public java.lang.String getArrivalDate() {
    java.lang.Object ref = arrivalDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        arrivalDate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string arrivalDate = 12;</code>
   */
  public com.google.protobuf.ByteString
      getArrivalDateBytes() {
    java.lang.Object ref = arrivalDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arrivalDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int32 duration = 13;
  public static final int DURATION_FIELD_NUMBER = 13;
  private int duration_;
  /**
   * <code>optional int32 duration = 13;</code>
   */
  public boolean hasDuration() {
    return ((bitField0_ & 0x00001000) == 0x00001000);
  }
  /**
   * <code>optional int32 duration = 13;</code>
   */
  public int getDuration() {
    return duration_;
  }

  // repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;
  public static final int ROOMS_FIELD_NUMBER = 14;
  private java.util.List<com.jactravel.monitoring.BookRoomInfo> rooms_;
  /**
   * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
   */
  public java.util.List<com.jactravel.monitoring.BookRoomInfo> getRoomsList() {
    return rooms_;
  }
  /**
   * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
   */
  public java.util.List<? extends com.jactravel.monitoring.BookRoomInfoOrBuilder> 
      getRoomsOrBuilderList() {
    return rooms_;
  }
  /**
   * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
   */
  public int getRoomsCount() {
    return rooms_.size();
  }
  /**
   * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
   */
  public com.jactravel.monitoring.BookRoomInfo getRooms(int index) {
    return rooms_.get(index);
  }
  /**
   * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
   */
  public com.jactravel.monitoring.BookRoomInfoOrBuilder getRoomsOrBuilder(
      int index) {
    return rooms_.get(index);
  }

  // optional int32 currencyID = 15;
  public static final int CURRENCYID_FIELD_NUMBER = 15;
  private int currencyID_;
  /**
   * <code>optional int32 currencyID = 15;</code>
   */
  public boolean hasCurrencyID() {
    return ((bitField0_ & 0x00002000) == 0x00002000);
  }
  /**
   * <code>optional int32 currencyID = 15;</code>
   */
  public int getCurrencyID() {
    return currencyID_;
  }

  // optional string preBookingToken = 16;
  public static final int PREBOOKINGTOKEN_FIELD_NUMBER = 16;
  private java.lang.Object preBookingToken_;
  /**
   * <code>optional string preBookingToken = 16;</code>
   */
  public boolean hasPreBookingToken() {
    return ((bitField0_ & 0x00004000) == 0x00004000);
  }
  /**
   * <code>optional string preBookingToken = 16;</code>
   */
  public java.lang.String getPreBookingToken() {
    java.lang.Object ref = preBookingToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        preBookingToken_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string preBookingToken = 16;</code>
   */
  public com.google.protobuf.ByteString
      getPreBookingTokenBytes() {
    java.lang.Object ref = preBookingToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      preBookingToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string errorMessage = 17;
  public static final int ERRORMESSAGE_FIELD_NUMBER = 17;
  private java.lang.Object errorMessage_;
  /**
   * <code>optional string errorMessage = 17;</code>
   */
  public boolean hasErrorMessage() {
    return ((bitField0_ & 0x00008000) == 0x00008000);
  }
  /**
   * <code>optional string errorMessage = 17;</code>
   */
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        errorMessage_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string errorMessage = 17;</code>
   */
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string errorStackTrace = 18;
  public static final int ERRORSTACKTRACE_FIELD_NUMBER = 18;
  private java.lang.Object errorStackTrace_;
  /**
   * <code>optional string errorStackTrace = 18;</code>
   */
  public boolean hasErrorStackTrace() {
    return ((bitField0_ & 0x00010000) == 0x00010000);
  }
  /**
   * <code>optional string errorStackTrace = 18;</code>
   */
  public java.lang.String getErrorStackTrace() {
    java.lang.Object ref = errorStackTrace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        errorStackTrace_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string errorStackTrace = 18;</code>
   */
  public com.google.protobuf.ByteString
      getErrorStackTraceBytes() {
    java.lang.Object ref = errorStackTrace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorStackTrace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    queryUUID_ = "";
    searchQueryUUID_ = "";
    preBookQueryUUID_ = "";
    searchProcessor_ = com.jactravel.monitoring.PlatformType.UnknownPlatform;
    host_ = "";
    startUtcTimestamp_ = "";
    endUtcTimestamp_ = "";
    tradeID_ = 0;
    brandID_ = 0;
    salesChannelID_ = 0;
    propertyID_ = 0;
    arrivalDate_ = "";
    duration_ = 0;
    rooms_ = java.util.Collections.emptyList();
    currencyID_ = 0;
    preBookingToken_ = "";
    errorMessage_ = "";
    errorStackTrace_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getQueryUUIDBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getSearchQueryUUIDBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getPreBookQueryUUIDBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeEnum(4, searchProcessor_.getNumber());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getHostBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBytes(6, getStartUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeBytes(7, getEndUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeInt32(8, tradeID_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeInt32(9, brandID_);
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeInt32(10, salesChannelID_);
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      output.writeInt32(11, propertyID_);
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      output.writeBytes(12, getArrivalDateBytes());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      output.writeInt32(13, duration_);
    }
    for (int i = 0; i < rooms_.size(); i++) {
      output.writeMessage(14, rooms_.get(i));
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      output.writeInt32(15, currencyID_);
    }
    if (((bitField0_ & 0x00004000) == 0x00004000)) {
      output.writeBytes(16, getPreBookingTokenBytes());
    }
    if (((bitField0_ & 0x00008000) == 0x00008000)) {
      output.writeBytes(17, getErrorMessageBytes());
    }
    if (((bitField0_ & 0x00010000) == 0x00010000)) {
      output.writeBytes(18, getErrorStackTraceBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getQueryUUIDBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getSearchQueryUUIDBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getPreBookQueryUUIDBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, searchProcessor_.getNumber());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getHostBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, getStartUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, getEndUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, tradeID_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, brandID_);
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, salesChannelID_);
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, propertyID_);
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, getArrivalDateBytes());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, duration_);
    }
    for (int i = 0; i < rooms_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, rooms_.get(i));
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, currencyID_);
    }
    if (((bitField0_ & 0x00004000) == 0x00004000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(16, getPreBookingTokenBytes());
    }
    if (((bitField0_ & 0x00008000) == 0x00008000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(17, getErrorMessageBytes());
    }
    if (((bitField0_ & 0x00010000) == 0x00010000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(18, getErrorStackTraceBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.jactravel.monitoring.BookRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jactravel.monitoring.BookRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jactravel.monitoring.BookRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jactravel.monitoring.BookRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jactravel.monitoring.BookRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.jactravel.monitoring.BookRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.jactravel.monitoring.BookRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.jactravel.monitoring.BookRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.jactravel.monitoring.BookRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.jactravel.monitoring.BookRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.jactravel.monitoring.BookRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Jactravel.Monitoring.BookRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.jactravel.monitoring.BookRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jactravel.monitoring.BookRequestProto.internal_static_Jactravel_Monitoring_BookRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jactravel.monitoring.BookRequestProto.internal_static_Jactravel_Monitoring_BookRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jactravel.monitoring.BookRequest.class, com.jactravel.monitoring.BookRequest.Builder.class);
    }

    // Construct using com.jactravel.monitoring.BookRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getRoomsFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      queryUUID_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      searchQueryUUID_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      preBookQueryUUID_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      searchProcessor_ = com.jactravel.monitoring.PlatformType.UnknownPlatform;
      bitField0_ = (bitField0_ & ~0x00000008);
      host_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      startUtcTimestamp_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      endUtcTimestamp_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      tradeID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      brandID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000100);
      salesChannelID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000200);
      propertyID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000400);
      arrivalDate_ = "";
      bitField0_ = (bitField0_ & ~0x00000800);
      duration_ = 0;
      bitField0_ = (bitField0_ & ~0x00001000);
      if (roomsBuilder_ == null) {
        rooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
      } else {
        roomsBuilder_.clear();
      }
      currencyID_ = 0;
      bitField0_ = (bitField0_ & ~0x00004000);
      preBookingToken_ = "";
      bitField0_ = (bitField0_ & ~0x00008000);
      errorMessage_ = "";
      bitField0_ = (bitField0_ & ~0x00010000);
      errorStackTrace_ = "";
      bitField0_ = (bitField0_ & ~0x00020000);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jactravel.monitoring.BookRequestProto.internal_static_Jactravel_Monitoring_BookRequest_descriptor;
    }

    public com.jactravel.monitoring.BookRequest getDefaultInstanceForType() {
      return com.jactravel.monitoring.BookRequest.getDefaultInstance();
    }

    public com.jactravel.monitoring.BookRequest build() {
      com.jactravel.monitoring.BookRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jactravel.monitoring.BookRequest buildPartial() {
      com.jactravel.monitoring.BookRequest result = new com.jactravel.monitoring.BookRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.queryUUID_ = queryUUID_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.searchQueryUUID_ = searchQueryUUID_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.preBookQueryUUID_ = preBookQueryUUID_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.searchProcessor_ = searchProcessor_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.host_ = host_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.startUtcTimestamp_ = startUtcTimestamp_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.endUtcTimestamp_ = endUtcTimestamp_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.tradeID_ = tradeID_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.brandID_ = brandID_;
      if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
        to_bitField0_ |= 0x00000200;
      }
      result.salesChannelID_ = salesChannelID_;
      if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
        to_bitField0_ |= 0x00000400;
      }
      result.propertyID_ = propertyID_;
      if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
        to_bitField0_ |= 0x00000800;
      }
      result.arrivalDate_ = arrivalDate_;
      if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
        to_bitField0_ |= 0x00001000;
      }
      result.duration_ = duration_;
      if (roomsBuilder_ == null) {
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          rooms_ = java.util.Collections.unmodifiableList(rooms_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.rooms_ = rooms_;
      } else {
        result.rooms_ = roomsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
        to_bitField0_ |= 0x00002000;
      }
      result.currencyID_ = currencyID_;
      if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
        to_bitField0_ |= 0x00004000;
      }
      result.preBookingToken_ = preBookingToken_;
      if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
        to_bitField0_ |= 0x00008000;
      }
      result.errorMessage_ = errorMessage_;
      if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
        to_bitField0_ |= 0x00010000;
      }
      result.errorStackTrace_ = errorStackTrace_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jactravel.monitoring.BookRequest) {
        return mergeFrom((com.jactravel.monitoring.BookRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jactravel.monitoring.BookRequest other) {
      if (other == com.jactravel.monitoring.BookRequest.getDefaultInstance()) return this;
      if (other.hasQueryUUID()) {
        bitField0_ |= 0x00000001;
        queryUUID_ = other.queryUUID_;
        onChanged();
      }
      if (other.hasSearchQueryUUID()) {
        bitField0_ |= 0x00000002;
        searchQueryUUID_ = other.searchQueryUUID_;
        onChanged();
      }
      if (other.hasPreBookQueryUUID()) {
        bitField0_ |= 0x00000004;
        preBookQueryUUID_ = other.preBookQueryUUID_;
        onChanged();
      }
      if (other.hasSearchProcessor()) {
        setSearchProcessor(other.getSearchProcessor());
      }
      if (other.hasHost()) {
        bitField0_ |= 0x00000010;
        host_ = other.host_;
        onChanged();
      }
      if (other.hasStartUtcTimestamp()) {
        bitField0_ |= 0x00000020;
        startUtcTimestamp_ = other.startUtcTimestamp_;
        onChanged();
      }
      if (other.hasEndUtcTimestamp()) {
        bitField0_ |= 0x00000040;
        endUtcTimestamp_ = other.endUtcTimestamp_;
        onChanged();
      }
      if (other.hasTradeID()) {
        setTradeID(other.getTradeID());
      }
      if (other.hasBrandID()) {
        setBrandID(other.getBrandID());
      }
      if (other.hasSalesChannelID()) {
        setSalesChannelID(other.getSalesChannelID());
      }
      if (other.hasPropertyID()) {
        setPropertyID(other.getPropertyID());
      }
      if (other.hasArrivalDate()) {
        bitField0_ |= 0x00000800;
        arrivalDate_ = other.arrivalDate_;
        onChanged();
      }
      if (other.hasDuration()) {
        setDuration(other.getDuration());
      }
      if (roomsBuilder_ == null) {
        if (!other.rooms_.isEmpty()) {
          if (rooms_.isEmpty()) {
            rooms_ = other.rooms_;
            bitField0_ = (bitField0_ & ~0x00002000);
          } else {
            ensureRoomsIsMutable();
            rooms_.addAll(other.rooms_);
          }
          onChanged();
        }
      } else {
        if (!other.rooms_.isEmpty()) {
          if (roomsBuilder_.isEmpty()) {
            roomsBuilder_.dispose();
            roomsBuilder_ = null;
            rooms_ = other.rooms_;
            bitField0_ = (bitField0_ & ~0x00002000);
            roomsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getRoomsFieldBuilder() : null;
          } else {
            roomsBuilder_.addAllMessages(other.rooms_);
          }
        }
      }
      if (other.hasCurrencyID()) {
        setCurrencyID(other.getCurrencyID());
      }
      if (other.hasPreBookingToken()) {
        bitField0_ |= 0x00008000;
        preBookingToken_ = other.preBookingToken_;
        onChanged();
      }
      if (other.hasErrorMessage()) {
        bitField0_ |= 0x00010000;
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      if (other.hasErrorStackTrace()) {
        bitField0_ |= 0x00020000;
        errorStackTrace_ = other.errorStackTrace_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jactravel.monitoring.BookRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jactravel.monitoring.BookRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string queryUUID = 1;
    private java.lang.Object queryUUID_ = "";
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public boolean hasQueryUUID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public java.lang.String getQueryUUID() {
      java.lang.Object ref = queryUUID_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        queryUUID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryUUIDBytes() {
      java.lang.Object ref = queryUUID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queryUUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public Builder setQueryUUID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      queryUUID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public Builder clearQueryUUID() {
      bitField0_ = (bitField0_ & ~0x00000001);
      queryUUID_ = getDefaultInstance().getQueryUUID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public Builder setQueryUUIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      queryUUID_ = value;
      onChanged();
      return this;
    }

    // optional string searchQueryUUID = 2;
    private java.lang.Object searchQueryUUID_ = "";
    /**
     * <code>optional string searchQueryUUID = 2;</code>
     */
    public boolean hasSearchQueryUUID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string searchQueryUUID = 2;</code>
     */
    public java.lang.String getSearchQueryUUID() {
      java.lang.Object ref = searchQueryUUID_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        searchQueryUUID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string searchQueryUUID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSearchQueryUUIDBytes() {
      java.lang.Object ref = searchQueryUUID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        searchQueryUUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string searchQueryUUID = 2;</code>
     */
    public Builder setSearchQueryUUID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      searchQueryUUID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string searchQueryUUID = 2;</code>
     */
    public Builder clearSearchQueryUUID() {
      bitField0_ = (bitField0_ & ~0x00000002);
      searchQueryUUID_ = getDefaultInstance().getSearchQueryUUID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string searchQueryUUID = 2;</code>
     */
    public Builder setSearchQueryUUIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      searchQueryUUID_ = value;
      onChanged();
      return this;
    }

    // optional string preBookQueryUUID = 3;
    private java.lang.Object preBookQueryUUID_ = "";
    /**
     * <code>optional string preBookQueryUUID = 3;</code>
     */
    public boolean hasPreBookQueryUUID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string preBookQueryUUID = 3;</code>
     */
    public java.lang.String getPreBookQueryUUID() {
      java.lang.Object ref = preBookQueryUUID_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        preBookQueryUUID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string preBookQueryUUID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPreBookQueryUUIDBytes() {
      java.lang.Object ref = preBookQueryUUID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preBookQueryUUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string preBookQueryUUID = 3;</code>
     */
    public Builder setPreBookQueryUUID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      preBookQueryUUID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string preBookQueryUUID = 3;</code>
     */
    public Builder clearPreBookQueryUUID() {
      bitField0_ = (bitField0_ & ~0x00000004);
      preBookQueryUUID_ = getDefaultInstance().getPreBookQueryUUID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string preBookQueryUUID = 3;</code>
     */
    public Builder setPreBookQueryUUIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      preBookQueryUUID_ = value;
      onChanged();
      return this;
    }

    // optional .Jactravel.Monitoring.PlatformType searchProcessor = 4;
    private com.jactravel.monitoring.PlatformType searchProcessor_ = com.jactravel.monitoring.PlatformType.UnknownPlatform;
    /**
     * <code>optional .Jactravel.Monitoring.PlatformType searchProcessor = 4;</code>
     */
    public boolean hasSearchProcessor() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Jactravel.Monitoring.PlatformType searchProcessor = 4;</code>
     */
    public com.jactravel.monitoring.PlatformType getSearchProcessor() {
      return searchProcessor_;
    }
    /**
     * <code>optional .Jactravel.Monitoring.PlatformType searchProcessor = 4;</code>
     */
    public Builder setSearchProcessor(com.jactravel.monitoring.PlatformType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      searchProcessor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Jactravel.Monitoring.PlatformType searchProcessor = 4;</code>
     */
    public Builder clearSearchProcessor() {
      bitField0_ = (bitField0_ & ~0x00000008);
      searchProcessor_ = com.jactravel.monitoring.PlatformType.UnknownPlatform;
      onChanged();
      return this;
    }

    // optional string host = 5;
    private java.lang.Object host_ = "";
    /**
     * <code>optional string host = 5;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string host = 5;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        host_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string host = 5;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string host = 5;</code>
     */
    public Builder setHost(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      host_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string host = 5;</code>
     */
    public Builder clearHost() {
      bitField0_ = (bitField0_ & ~0x00000010);
      host_ = getDefaultInstance().getHost();
      onChanged();
      return this;
    }
    /**
     * <code>optional string host = 5;</code>
     */
    public Builder setHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      host_ = value;
      onChanged();
      return this;
    }

    // optional string startUtcTimestamp = 6;
    private java.lang.Object startUtcTimestamp_ = "";
    /**
     * <code>optional string startUtcTimestamp = 6;</code>
     */
    public boolean hasStartUtcTimestamp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string startUtcTimestamp = 6;</code>
     */
    public java.lang.String getStartUtcTimestamp() {
      java.lang.Object ref = startUtcTimestamp_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        startUtcTimestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string startUtcTimestamp = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStartUtcTimestampBytes() {
      java.lang.Object ref = startUtcTimestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startUtcTimestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string startUtcTimestamp = 6;</code>
     */
    public Builder setStartUtcTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      startUtcTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string startUtcTimestamp = 6;</code>
     */
    public Builder clearStartUtcTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000020);
      startUtcTimestamp_ = getDefaultInstance().getStartUtcTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string startUtcTimestamp = 6;</code>
     */
    public Builder setStartUtcTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      startUtcTimestamp_ = value;
      onChanged();
      return this;
    }

    // optional string endUtcTimestamp = 7;
    private java.lang.Object endUtcTimestamp_ = "";
    /**
     * <code>optional string endUtcTimestamp = 7;</code>
     */
    public boolean hasEndUtcTimestamp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string endUtcTimestamp = 7;</code>
     */
    public java.lang.String getEndUtcTimestamp() {
      java.lang.Object ref = endUtcTimestamp_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        endUtcTimestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string endUtcTimestamp = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEndUtcTimestampBytes() {
      java.lang.Object ref = endUtcTimestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endUtcTimestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string endUtcTimestamp = 7;</code>
     */
    public Builder setEndUtcTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      endUtcTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string endUtcTimestamp = 7;</code>
     */
    public Builder clearEndUtcTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      endUtcTimestamp_ = getDefaultInstance().getEndUtcTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string endUtcTimestamp = 7;</code>
     */
    public Builder setEndUtcTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      endUtcTimestamp_ = value;
      onChanged();
      return this;
    }

    // optional int32 tradeID = 8;
    private int tradeID_ ;
    /**
     * <code>optional int32 tradeID = 8;</code>
     */
    public boolean hasTradeID() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 tradeID = 8;</code>
     */
    public int getTradeID() {
      return tradeID_;
    }
    /**
     * <code>optional int32 tradeID = 8;</code>
     */
    public Builder setTradeID(int value) {
      bitField0_ |= 0x00000080;
      tradeID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 tradeID = 8;</code>
     */
    public Builder clearTradeID() {
      bitField0_ = (bitField0_ & ~0x00000080);
      tradeID_ = 0;
      onChanged();
      return this;
    }

    // optional int32 brandID = 9;
    private int brandID_ ;
    /**
     * <code>optional int32 brandID = 9;</code>
     */
    public boolean hasBrandID() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 brandID = 9;</code>
     */
    public int getBrandID() {
      return brandID_;
    }
    /**
     * <code>optional int32 brandID = 9;</code>
     */
    public Builder setBrandID(int value) {
      bitField0_ |= 0x00000100;
      brandID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 brandID = 9;</code>
     */
    public Builder clearBrandID() {
      bitField0_ = (bitField0_ & ~0x00000100);
      brandID_ = 0;
      onChanged();
      return this;
    }

    // optional int32 salesChannelID = 10;
    private int salesChannelID_ ;
    /**
     * <code>optional int32 salesChannelID = 10;</code>
     */
    public boolean hasSalesChannelID() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 salesChannelID = 10;</code>
     */
    public int getSalesChannelID() {
      return salesChannelID_;
    }
    /**
     * <code>optional int32 salesChannelID = 10;</code>
     */
    public Builder setSalesChannelID(int value) {
      bitField0_ |= 0x00000200;
      salesChannelID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 salesChannelID = 10;</code>
     */
    public Builder clearSalesChannelID() {
      bitField0_ = (bitField0_ & ~0x00000200);
      salesChannelID_ = 0;
      onChanged();
      return this;
    }

    // optional int32 propertyID = 11;
    private int propertyID_ ;
    /**
     * <code>optional int32 propertyID = 11;</code>
     */
    public boolean hasPropertyID() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 propertyID = 11;</code>
     */
    public int getPropertyID() {
      return propertyID_;
    }
    /**
     * <code>optional int32 propertyID = 11;</code>
     */
    public Builder setPropertyID(int value) {
      bitField0_ |= 0x00000400;
      propertyID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 propertyID = 11;</code>
     */
    public Builder clearPropertyID() {
      bitField0_ = (bitField0_ & ~0x00000400);
      propertyID_ = 0;
      onChanged();
      return this;
    }

    // optional string arrivalDate = 12;
    private java.lang.Object arrivalDate_ = "";
    /**
     * <code>optional string arrivalDate = 12;</code>
     */
    public boolean hasArrivalDate() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string arrivalDate = 12;</code>
     */
    public java.lang.String getArrivalDate() {
      java.lang.Object ref = arrivalDate_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        arrivalDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string arrivalDate = 12;</code>
     */
    public com.google.protobuf.ByteString
        getArrivalDateBytes() {
      java.lang.Object ref = arrivalDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arrivalDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string arrivalDate = 12;</code>
     */
    public Builder setArrivalDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      arrivalDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string arrivalDate = 12;</code>
     */
    public Builder clearArrivalDate() {
      bitField0_ = (bitField0_ & ~0x00000800);
      arrivalDate_ = getDefaultInstance().getArrivalDate();
      onChanged();
      return this;
    }
    /**
     * <code>optional string arrivalDate = 12;</code>
     */
    public Builder setArrivalDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      arrivalDate_ = value;
      onChanged();
      return this;
    }

    // optional int32 duration = 13;
    private int duration_ ;
    /**
     * <code>optional int32 duration = 13;</code>
     */
    public boolean hasDuration() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 duration = 13;</code>
     */
    public int getDuration() {
      return duration_;
    }
    /**
     * <code>optional int32 duration = 13;</code>
     */
    public Builder setDuration(int value) {
      bitField0_ |= 0x00001000;
      duration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 duration = 13;</code>
     */
    public Builder clearDuration() {
      bitField0_ = (bitField0_ & ~0x00001000);
      duration_ = 0;
      onChanged();
      return this;
    }

    // repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;
    private java.util.List<com.jactravel.monitoring.BookRoomInfo> rooms_ =
      java.util.Collections.emptyList();
    private void ensureRoomsIsMutable() {
      if (!((bitField0_ & 0x00002000) == 0x00002000)) {
        rooms_ = new java.util.ArrayList<com.jactravel.monitoring.BookRoomInfo>(rooms_);
        bitField0_ |= 0x00002000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.jactravel.monitoring.BookRoomInfo, com.jactravel.monitoring.BookRoomInfo.Builder, com.jactravel.monitoring.BookRoomInfoOrBuilder> roomsBuilder_;

    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public java.util.List<com.jactravel.monitoring.BookRoomInfo> getRoomsList() {
      if (roomsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rooms_);
      } else {
        return roomsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public int getRoomsCount() {
      if (roomsBuilder_ == null) {
        return rooms_.size();
      } else {
        return roomsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public com.jactravel.monitoring.BookRoomInfo getRooms(int index) {
      if (roomsBuilder_ == null) {
        return rooms_.get(index);
      } else {
        return roomsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public Builder setRooms(
        int index, com.jactravel.monitoring.BookRoomInfo value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.set(index, value);
        onChanged();
      } else {
        roomsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public Builder setRooms(
        int index, com.jactravel.monitoring.BookRoomInfo.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.set(index, builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public Builder addRooms(com.jactravel.monitoring.BookRoomInfo value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.add(value);
        onChanged();
      } else {
        roomsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public Builder addRooms(
        int index, com.jactravel.monitoring.BookRoomInfo value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.add(index, value);
        onChanged();
      } else {
        roomsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public Builder addRooms(
        com.jactravel.monitoring.BookRoomInfo.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.add(builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public Builder addRooms(
        int index, com.jactravel.monitoring.BookRoomInfo.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.add(index, builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public Builder addAllRooms(
        java.lang.Iterable<? extends com.jactravel.monitoring.BookRoomInfo> values) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        super.addAll(values, rooms_);
        onChanged();
      } else {
        roomsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public Builder clearRooms() {
      if (roomsBuilder_ == null) {
        rooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
      } else {
        roomsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public Builder removeRooms(int index) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.remove(index);
        onChanged();
      } else {
        roomsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public com.jactravel.monitoring.BookRoomInfo.Builder getRoomsBuilder(
        int index) {
      return getRoomsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public com.jactravel.monitoring.BookRoomInfoOrBuilder getRoomsOrBuilder(
        int index) {
      if (roomsBuilder_ == null) {
        return rooms_.get(index);  } else {
        return roomsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public java.util.List<? extends com.jactravel.monitoring.BookRoomInfoOrBuilder> 
         getRoomsOrBuilderList() {
      if (roomsBuilder_ != null) {
        return roomsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rooms_);
      }
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public com.jactravel.monitoring.BookRoomInfo.Builder addRoomsBuilder() {
      return getRoomsFieldBuilder().addBuilder(
          com.jactravel.monitoring.BookRoomInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public com.jactravel.monitoring.BookRoomInfo.Builder addRoomsBuilder(
        int index) {
      return getRoomsFieldBuilder().addBuilder(
          index, com.jactravel.monitoring.BookRoomInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .Jactravel.Monitoring.BookRoomInfo rooms = 14;</code>
     */
    public java.util.List<com.jactravel.monitoring.BookRoomInfo.Builder> 
         getRoomsBuilderList() {
      return getRoomsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.jactravel.monitoring.BookRoomInfo, com.jactravel.monitoring.BookRoomInfo.Builder, com.jactravel.monitoring.BookRoomInfoOrBuilder> 
        getRoomsFieldBuilder() {
      if (roomsBuilder_ == null) {
        roomsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.jactravel.monitoring.BookRoomInfo, com.jactravel.monitoring.BookRoomInfo.Builder, com.jactravel.monitoring.BookRoomInfoOrBuilder>(
                rooms_,
                ((bitField0_ & 0x00002000) == 0x00002000),
                getParentForChildren(),
                isClean());
        rooms_ = null;
      }
      return roomsBuilder_;
    }

    // optional int32 currencyID = 15;
    private int currencyID_ ;
    /**
     * <code>optional int32 currencyID = 15;</code>
     */
    public boolean hasCurrencyID() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int32 currencyID = 15;</code>
     */
    public int getCurrencyID() {
      return currencyID_;
    }
    /**
     * <code>optional int32 currencyID = 15;</code>
     */
    public Builder setCurrencyID(int value) {
      bitField0_ |= 0x00004000;
      currencyID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 currencyID = 15;</code>
     */
    public Builder clearCurrencyID() {
      bitField0_ = (bitField0_ & ~0x00004000);
      currencyID_ = 0;
      onChanged();
      return this;
    }

    // optional string preBookingToken = 16;
    private java.lang.Object preBookingToken_ = "";
    /**
     * <code>optional string preBookingToken = 16;</code>
     */
    public boolean hasPreBookingToken() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional string preBookingToken = 16;</code>
     */
    public java.lang.String getPreBookingToken() {
      java.lang.Object ref = preBookingToken_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        preBookingToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string preBookingToken = 16;</code>
     */
    public com.google.protobuf.ByteString
        getPreBookingTokenBytes() {
      java.lang.Object ref = preBookingToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preBookingToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string preBookingToken = 16;</code>
     */
    public Builder setPreBookingToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
      preBookingToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string preBookingToken = 16;</code>
     */
    public Builder clearPreBookingToken() {
      bitField0_ = (bitField0_ & ~0x00008000);
      preBookingToken_ = getDefaultInstance().getPreBookingToken();
      onChanged();
      return this;
    }
    /**
     * <code>optional string preBookingToken = 16;</code>
     */
    public Builder setPreBookingTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
      preBookingToken_ = value;
      onChanged();
      return this;
    }

    // optional string errorMessage = 17;
    private java.lang.Object errorMessage_ = "";
    /**
     * <code>optional string errorMessage = 17;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional string errorMessage = 17;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string errorMessage = 17;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string errorMessage = 17;</code>
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorMessage = 17;</code>
     */
    public Builder clearErrorMessage() {
      bitField0_ = (bitField0_ & ~0x00010000);
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorMessage = 17;</code>
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
      errorMessage_ = value;
      onChanged();
      return this;
    }

    // optional string errorStackTrace = 18;
    private java.lang.Object errorStackTrace_ = "";
    /**
     * <code>optional string errorStackTrace = 18;</code>
     */
    public boolean hasErrorStackTrace() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>optional string errorStackTrace = 18;</code>
     */
    public java.lang.String getErrorStackTrace() {
      java.lang.Object ref = errorStackTrace_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        errorStackTrace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string errorStackTrace = 18;</code>
     */
    public com.google.protobuf.ByteString
        getErrorStackTraceBytes() {
      java.lang.Object ref = errorStackTrace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorStackTrace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string errorStackTrace = 18;</code>
     */
    public Builder setErrorStackTrace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
      errorStackTrace_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorStackTrace = 18;</code>
     */
    public Builder clearErrorStackTrace() {
      bitField0_ = (bitField0_ & ~0x00020000);
      errorStackTrace_ = getDefaultInstance().getErrorStackTrace();
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorStackTrace = 18;</code>
     */
    public Builder setErrorStackTraceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
      errorStackTrace_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Jactravel.Monitoring.BookRequest)
  }

  static {
    defaultInstance = new BookRequest(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Jactravel.Monitoring.BookRequest)
}

