// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CMIBatchRequest.proto

package com.jactravel.monitoring;

public final class CMIBatchRequestProto {
  private CMIBatchRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Jactravel_Monitoring_CMIBatchRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Jactravel_Monitoring_CMIBatchRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025CMIBatchRequest.proto\022\024Jactravel.Monit" +
      "oring\032\022PlatformType.proto\032\022CMIQueryType." +
      "proto\"\244\002\n\017CMIBatchRequest\022\021\n\tqueryUUID\030\001" +
      " \001(\t\022\022\n\nsupplierIP\030\002 \001(\t\0228\n\014CMIQueryType" +
      "\030\003 \001(\0162\".Jactravel.Monitoring.CMIQueryTy" +
      "pe\022\014\n\004host\030\005 \001(\t\022\033\n\023requestUtcTimestamp\030" +
      "\006 \001(\t\022\034\n\024responseUtcTimestamp\030\007 \001(\t\022\022\n\nr" +
      "equestXML\030\n \001(\t\022\023\n\013responseXML\030\013 \001(\t\022\017\n\007" +
      "success\030\r \001(\t\022\024\n\014errorMessage\030\016 \001(\t\022\027\n\017e" +
      "rrorStackTrace\030\021 \001(\tB2\n\030com.jactravel.mo",
      "nitoringB\024CMIBatchRequestProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Jactravel_Monitoring_CMIBatchRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Jactravel_Monitoring_CMIBatchRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Jactravel_Monitoring_CMIBatchRequest_descriptor,
              new java.lang.String[] { "QueryUUID", "SupplierIP", "CMIQueryType", "Host", "RequestUtcTimestamp", "ResponseUtcTimestamp", "RequestXML", "ResponseXML", "Success", "ErrorMessage", "ErrorStackTrace", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.jactravel.monitoring.PlatformTypeProto.getDescriptor(),
          com.jactravel.monitoring.CMIQueryTypeProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
