// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CMIBatchRequest.proto

package com.jactravel.monitoring;

public interface CMIBatchRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string queryUUID = 1;
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  boolean hasQueryUUID();
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  java.lang.String getQueryUUID();
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  com.google.protobuf.ByteString
      getQueryUUIDBytes();

  // optional string supplierIP = 2;
  /**
   * <code>optional string supplierIP = 2;</code>
   */
  boolean hasSupplierIP();
  /**
   * <code>optional string supplierIP = 2;</code>
   */
  java.lang.String getSupplierIP();
  /**
   * <code>optional string supplierIP = 2;</code>
   */
  com.google.protobuf.ByteString
      getSupplierIPBytes();

  // optional .Jactravel.Monitoring.CMIQueryType CMIQueryType = 3;
  /**
   * <code>optional .Jactravel.Monitoring.CMIQueryType CMIQueryType = 3;</code>
   */
  boolean hasCMIQueryType();
  /**
   * <code>optional .Jactravel.Monitoring.CMIQueryType CMIQueryType = 3;</code>
   */
  com.jactravel.monitoring.CMIQueryType getCMIQueryType();

  // optional string host = 5;
  /**
   * <code>optional string host = 5;</code>
   */
  boolean hasHost();
  /**
   * <code>optional string host = 5;</code>
   */
  java.lang.String getHost();
  /**
   * <code>optional string host = 5;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  // optional string requestUtcTimestamp = 6;
  /**
   * <code>optional string requestUtcTimestamp = 6;</code>
   */
  boolean hasRequestUtcTimestamp();
  /**
   * <code>optional string requestUtcTimestamp = 6;</code>
   */
  java.lang.String getRequestUtcTimestamp();
  /**
   * <code>optional string requestUtcTimestamp = 6;</code>
   */
  com.google.protobuf.ByteString
      getRequestUtcTimestampBytes();

  // optional string responseUtcTimestamp = 7;
  /**
   * <code>optional string responseUtcTimestamp = 7;</code>
   */
  boolean hasResponseUtcTimestamp();
  /**
   * <code>optional string responseUtcTimestamp = 7;</code>
   */
  java.lang.String getResponseUtcTimestamp();
  /**
   * <code>optional string responseUtcTimestamp = 7;</code>
   */
  com.google.protobuf.ByteString
      getResponseUtcTimestampBytes();

  // optional string requestXML = 10;
  /**
   * <code>optional string requestXML = 10;</code>
   */
  boolean hasRequestXML();
  /**
   * <code>optional string requestXML = 10;</code>
   */
  java.lang.String getRequestXML();
  /**
   * <code>optional string requestXML = 10;</code>
   */
  com.google.protobuf.ByteString
      getRequestXMLBytes();

  // optional string responseXML = 11;
  /**
   * <code>optional string responseXML = 11;</code>
   */
  boolean hasResponseXML();
  /**
   * <code>optional string responseXML = 11;</code>
   */
  java.lang.String getResponseXML();
  /**
   * <code>optional string responseXML = 11;</code>
   */
  com.google.protobuf.ByteString
      getResponseXMLBytes();

  // optional string login = 12;
  /**
   * <code>optional string login = 12;</code>
   */
  boolean hasLogin();
  /**
   * <code>optional string login = 12;</code>
   */
  java.lang.String getLogin();
  /**
   * <code>optional string login = 12;</code>
   */
  com.google.protobuf.ByteString
      getLoginBytes();

  // optional string propertyCode = 13;
  /**
   * <code>optional string propertyCode = 13;</code>
   */
  boolean hasPropertyCode();
  /**
   * <code>optional string propertyCode = 13;</code>
   */
  java.lang.String getPropertyCode();
  /**
   * <code>optional string propertyCode = 13;</code>
   */
  com.google.protobuf.ByteString
      getPropertyCodeBytes();

  // optional string success = 14;
  /**
   * <code>optional string success = 14;</code>
   */
  boolean hasSuccess();
  /**
   * <code>optional string success = 14;</code>
   */
  java.lang.String getSuccess();
  /**
   * <code>optional string success = 14;</code>
   */
  com.google.protobuf.ByteString
      getSuccessBytes();

  // optional string errorMessage = 15;
  /**
   * <code>optional string errorMessage = 15;</code>
   */
  boolean hasErrorMessage();
  /**
   * <code>optional string errorMessage = 15;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>optional string errorMessage = 15;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  // optional string errorStackTrace = 16;
  /**
   * <code>optional string errorStackTrace = 16;</code>
   */
  boolean hasErrorStackTrace();
  /**
   * <code>optional string errorStackTrace = 16;</code>
   */
  java.lang.String getErrorStackTrace();
  /**
   * <code>optional string errorStackTrace = 16;</code>
   */
  com.google.protobuf.ByteString
      getErrorStackTraceBytes();
}
