// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CMIQueryType.proto

package com.jactravel.monitoring;

public final class CMIQueryTypeProto {
  private CMIQueryTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022CMIQueryType.proto\022\024Jactravel.Monitori" +
      "ng*\316\003\n\014CMIQueryType\022\017\n\013ServiceInfo\020\001\022\r\n\t" +
      "GetPrices\020\002\022\016\n\nSavePrices\020\003\022\014\n\010GetRooms\020" +
      "\004\022\017\n\013ManageRooms\020\005\022\021\n\rGetAllocation\020\006\022\023\n" +
      "\017GetReservations\020\007\022\023\n\017RoomAndRateCode\020\010\022" +
      "\024\n\020RateAndInventory\020\t\022\032\n\026RateAndInventor" +
      "yUpdate\020\n\022\036\n\032BulkRateAndInventoryUpdate\020" +
      "\013\022\017\n\013GetProperty\020\014\022\017\n\013GetRoomType\020\r\022\022\n\016G" +
      "etReservation\020\016\022\031\n\025SetConfirmationStatus" +
      "\020\017\022\024\n\020GetSpecialOffers\020\020\022\023\n\017AddSpecialOf",
      "fer\020\021\022\025\n\021AmendSpecialOffer\020\022\022\026\n\022CancelSp" +
      "ecialOffer\020\023\022\027\n\023OTA_HotelAvailNotif\020\024\022\034\n" +
      "\030OTA_HotelRateAmountNotif\020\025B/\n\030com.jactr" +
      "avel.monitoringB\021CMIQueryTypeProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
