// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CMIQueryType.proto

package com.jactravel.monitoring;

/**
 * Protobuf enum {@code Jactravel.Monitoring.CMIQueryType}
 */
public enum CMIQueryType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ServiceInfo = 1;</code>
   */
  ServiceInfo(0, 1),
  /**
   * <code>GetPrices = 2;</code>
   */
  GetPrices(1, 2),
  /**
   * <code>SavePrices = 3;</code>
   */
  SavePrices(2, 3),
  /**
   * <code>GetRooms = 4;</code>
   */
  GetRooms(3, 4),
  /**
   * <code>ManageRooms = 5;</code>
   */
  ManageRooms(4, 5),
  /**
   * <code>GetAllocation = 6;</code>
   */
  GetAllocation(5, 6),
  /**
   * <code>GetReservations = 7;</code>
   */
  GetReservations(6, 7),
  /**
   * <code>RoomAndRateCode = 8;</code>
   */
  RoomAndRateCode(7, 8),
  /**
   * <code>RateAndInventory = 9;</code>
   */
  RateAndInventory(8, 9),
  /**
   * <code>RateAndInventoryUpdate = 10;</code>
   */
  RateAndInventoryUpdate(9, 10),
  /**
   * <code>BulkRateAndInventoryUpdate = 11;</code>
   */
  BulkRateAndInventoryUpdate(10, 11),
  /**
   * <code>GetProperty = 12;</code>
   */
  GetProperty(11, 12),
  /**
   * <code>GetRoomType = 13;</code>
   */
  GetRoomType(12, 13),
  /**
   * <code>GetReservation = 14;</code>
   */
  GetReservation(13, 14),
  /**
   * <code>SetConfirmationStatus = 15;</code>
   */
  SetConfirmationStatus(14, 15),
  /**
   * <code>GetSpecialOffers = 16;</code>
   */
  GetSpecialOffers(15, 16),
  /**
   * <code>AddSpecialOffer = 17;</code>
   */
  AddSpecialOffer(16, 17),
  /**
   * <code>AmendSpecialOffer = 18;</code>
   */
  AmendSpecialOffer(17, 18),
  /**
   * <code>CancelSpecialOffer = 19;</code>
   */
  CancelSpecialOffer(18, 19),
  /**
   * <code>OTA_HotelAvailNotif = 20;</code>
   */
  OTA_HotelAvailNotif(19, 20),
  /**
   * <code>OTA_HotelRateAmountNotif = 21;</code>
   */
  OTA_HotelRateAmountNotif(20, 21),
  ;

  /**
   * <code>ServiceInfo = 1;</code>
   */
  public static final int ServiceInfo_VALUE = 1;
  /**
   * <code>GetPrices = 2;</code>
   */
  public static final int GetPrices_VALUE = 2;
  /**
   * <code>SavePrices = 3;</code>
   */
  public static final int SavePrices_VALUE = 3;
  /**
   * <code>GetRooms = 4;</code>
   */
  public static final int GetRooms_VALUE = 4;
  /**
   * <code>ManageRooms = 5;</code>
   */
  public static final int ManageRooms_VALUE = 5;
  /**
   * <code>GetAllocation = 6;</code>
   */
  public static final int GetAllocation_VALUE = 6;
  /**
   * <code>GetReservations = 7;</code>
   */
  public static final int GetReservations_VALUE = 7;
  /**
   * <code>RoomAndRateCode = 8;</code>
   */
  public static final int RoomAndRateCode_VALUE = 8;
  /**
   * <code>RateAndInventory = 9;</code>
   */
  public static final int RateAndInventory_VALUE = 9;
  /**
   * <code>RateAndInventoryUpdate = 10;</code>
   */
  public static final int RateAndInventoryUpdate_VALUE = 10;
  /**
   * <code>BulkRateAndInventoryUpdate = 11;</code>
   */
  public static final int BulkRateAndInventoryUpdate_VALUE = 11;
  /**
   * <code>GetProperty = 12;</code>
   */
  public static final int GetProperty_VALUE = 12;
  /**
   * <code>GetRoomType = 13;</code>
   */
  public static final int GetRoomType_VALUE = 13;
  /**
   * <code>GetReservation = 14;</code>
   */
  public static final int GetReservation_VALUE = 14;
  /**
   * <code>SetConfirmationStatus = 15;</code>
   */
  public static final int SetConfirmationStatus_VALUE = 15;
  /**
   * <code>GetSpecialOffers = 16;</code>
   */
  public static final int GetSpecialOffers_VALUE = 16;
  /**
   * <code>AddSpecialOffer = 17;</code>
   */
  public static final int AddSpecialOffer_VALUE = 17;
  /**
   * <code>AmendSpecialOffer = 18;</code>
   */
  public static final int AmendSpecialOffer_VALUE = 18;
  /**
   * <code>CancelSpecialOffer = 19;</code>
   */
  public static final int CancelSpecialOffer_VALUE = 19;
  /**
   * <code>OTA_HotelAvailNotif = 20;</code>
   */
  public static final int OTA_HotelAvailNotif_VALUE = 20;
  /**
   * <code>OTA_HotelRateAmountNotif = 21;</code>
   */
  public static final int OTA_HotelRateAmountNotif_VALUE = 21;


  public final int getNumber() { return value; }

  public static CMIQueryType valueOf(int value) {
    switch (value) {
      case 1: return ServiceInfo;
      case 2: return GetPrices;
      case 3: return SavePrices;
      case 4: return GetRooms;
      case 5: return ManageRooms;
      case 6: return GetAllocation;
      case 7: return GetReservations;
      case 8: return RoomAndRateCode;
      case 9: return RateAndInventory;
      case 10: return RateAndInventoryUpdate;
      case 11: return BulkRateAndInventoryUpdate;
      case 12: return GetProperty;
      case 13: return GetRoomType;
      case 14: return GetReservation;
      case 15: return SetConfirmationStatus;
      case 16: return GetSpecialOffers;
      case 17: return AddSpecialOffer;
      case 18: return AmendSpecialOffer;
      case 19: return CancelSpecialOffer;
      case 20: return OTA_HotelAvailNotif;
      case 21: return OTA_HotelRateAmountNotif;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CMIQueryType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<CMIQueryType>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CMIQueryType>() {
          public CMIQueryType findValueByNumber(int number) {
            return CMIQueryType.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.jactravel.monitoring.CMIQueryTypeProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final CMIQueryType[] VALUES = values();

  public static CMIQueryType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private CMIQueryType(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Jactravel.Monitoring.CMIQueryType)
}

