// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchReport.proto

package com.jactravel.monitoring;

/**
 * Protobuf enum {@code Jactravel.Monitoring.GeoLevel}
 */
public enum GeoLevel
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UnknownGeoLevel = 0;</code>
   */
  UnknownGeoLevel(0, 0),
  /**
   * <code>Country = 1;</code>
   */
  Country(1, 1),
  /**
   * <code>Region = 2;</code>
   */
  Region(2, 2),
  /**
   * <code>Resort = 3;</code>
   */
  Resort(3, 3),
  /**
   * <code>PropertyReference = 4;</code>
   */
  PropertyReference(4, 4),
  /**
   * <code>PropertyID = 5;</code>
   */
  PropertyID(5, 5),
  ;

  /**
   * <code>UnknownGeoLevel = 0;</code>
   */
  public static final int UnknownGeoLevel_VALUE = 0;
  /**
   * <code>Country = 1;</code>
   */
  public static final int Country_VALUE = 1;
  /**
   * <code>Region = 2;</code>
   */
  public static final int Region_VALUE = 2;
  /**
   * <code>Resort = 3;</code>
   */
  public static final int Resort_VALUE = 3;
  /**
   * <code>PropertyReference = 4;</code>
   */
  public static final int PropertyReference_VALUE = 4;
  /**
   * <code>PropertyID = 5;</code>
   */
  public static final int PropertyID_VALUE = 5;


  public final int getNumber() { return value; }

  public static GeoLevel valueOf(int value) {
    switch (value) {
      case 0: return UnknownGeoLevel;
      case 1: return Country;
      case 2: return Region;
      case 3: return Resort;
      case 4: return PropertyReference;
      case 5: return PropertyID;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GeoLevel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<GeoLevel>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GeoLevel>() {
          public GeoLevel findValueByNumber(int number) {
            return GeoLevel.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.jactravel.monitoring.SearchReportProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final GeoLevel[] VALUES = values();

  public static GeoLevel valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private GeoLevel(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Jactravel.Monitoring.GeoLevel)
}

