// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlatformType.proto

package com.jactravel.monitoring;

public final class PlatformTypeProto {
  private PlatformTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022PlatformType.proto\022\024Jactravel.Monitori" +
      "ng*\266\001\n\014PlatformType\022\023\n\017UnknownPlatform\020\000" +
      "\022\010\n\004Grid\020\001\022\013\n\007IVector\020\002\022\020\n\014TravelStudio\020" +
      "\003\022\027\n\023TravelStudioAdapter\020\004\022\010\n\004IVCC\020\005\022\014\n\010" +
      "CMIPrice\020\006\022\t\n\005IVWeb\020\007\022\t\n\005TSCMQ\020\010\022\014\n\010IVNa" +
      "tive\020\t\022\010\n\004IVSM\020\n\022\t\n\005IVOTA\020\013B/\n\030com.jactr" +
      "avel.monitoringB\021PlatformTypeProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
