// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PreBookRequest.proto

package com.jactravel.monitoring;

public final class PreBookRequestProto {
  private PreBookRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Jactravel_Monitoring_PreBookRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Jactravel_Monitoring_PreBookRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024PreBookRequest.proto\022\024Jactravel.Monito" +
      "ring\032\022PlatformType.proto\032\022BookRoomInfo.p" +
      "roto\"\220\003\n\016PreBookRequest\022\021\n\tqueryUUID\030\001 \001" +
      "(\t\022\027\n\017searchQueryUUID\030\002 \001(\t\022;\n\017searchPro" +
      "cessor\030\003 \001(\0162\".Jactravel.Monitoring.Plat" +
      "formType\022\014\n\004host\030\004 \001(\t\022\031\n\021startUtcTimest" +
      "amp\030\005 \001(\t\022\027\n\017endUtcTimestamp\030\006 \001(\t\022\017\n\007tr" +
      "adeID\030\007 \001(\005\022\017\n\007brandID\030\010 \001(\005\022\026\n\016salesCha" +
      "nnelID\030\t \001(\005\022\022\n\npropertyID\030\n \001(\005\022\023\n\013arri" +
      "valDate\030\013 \001(\t\022\020\n\010duration\030\014 \001(\005\0221\n\005rooms",
      "\030\r \003(\0132\".Jactravel.Monitoring.BookRoomIn" +
      "fo\022\022\n\ncurrencyID\030\016 \001(\005\022\027\n\017preBookingToke" +
      "n\030\017 \001(\tB1\n\030com.jactravel.monitoringB\023Pre" +
      "BookRequestProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Jactravel_Monitoring_PreBookRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Jactravel_Monitoring_PreBookRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Jactravel_Monitoring_PreBookRequest_descriptor,
              new java.lang.String[] { "QueryUUID", "SearchQueryUUID", "SearchProcessor", "Host", "StartUtcTimestamp", "EndUtcTimestamp", "TradeID", "BrandID", "SalesChannelID", "PropertyID", "ArrivalDate", "Duration", "Rooms", "CurrencyID", "PreBookingToken", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.jactravel.monitoring.PlatformTypeProto.getDescriptor(),
          com.jactravel.monitoring.BookRoomInfoProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
