// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueryProxyRequest.proto

package com.jactravel.monitoring;

public final class QueryProxyRequestProto {
  private QueryProxyRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Jactravel_Monitoring_QueryProxyRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Jactravel_Monitoring_QueryProxyRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027QueryProxyRequest.proto\022\024Jactravel.Mon" +
      "itoring\032\022PlatformType.proto\"\350\003\n\021QueryPro" +
      "xyRequest\022\021\n\tqueryUUID\030\001 \001(\t\022\020\n\010clientIP" +
      "\030\002 \001(\t\0228\n\017searchQueryType\030\003 \001(\0162\037.Jactra" +
      "vel.Monitoring.QueryType\022\014\n\004host\030\005 \001(\t\022!" +
      "\n\031clientRequestUtcTimestamp\030\006 \001(\t\022\"\n\032cli" +
      "entResponseUtcTimestamp\030\007 \001(\t\022$\n\034forward" +
      "edRequestUtcTimestamp\030\010 \001(\t\022%\n\035forwarded" +
      "ResponseUtcTimestamp\030\t \001(\t\022\022\n\nrequestXML" +
      "\030\n \001(\t\022\023\n\013responseXML\030\013 \001(\t\022\027\n\017xmlBookin",
      "gLogin\030\014 \001(\t\022\017\n\007success\030\r \001(\t\022\024\n\014errorMe" +
      "ssage\030\016 \001(\t\022<\n\020requestProcessor\030\017 \001(\0162\"." +
      "Jactravel.Monitoring.PlatformType\022\022\n\nreq" +
      "uestURL\030\020 \001(\t\022\027\n\017errorStackTrace\030\021 \001(\t*\220" +
      "\001\n\tQueryType\022\021\n\rUnknownSearch\020\000\022\021\n\rIVect" +
      "orSearch\020\001\022\026\n\022TravelStudioSearch\020\002\022\017\n\013IV" +
      "ectorBook\020\003\022\022\n\016IVectorPreBook\020\004\022\027\n\023IVect" +
      "orCancellation\020\005\022\007\n\003CMI\020\006B4\n\030com.jactrav" +
      "el.monitoringB\026QueryProxyRequestProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Jactravel_Monitoring_QueryProxyRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Jactravel_Monitoring_QueryProxyRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Jactravel_Monitoring_QueryProxyRequest_descriptor,
              new java.lang.String[] { "QueryUUID", "ClientIP", "SearchQueryType", "Host", "ClientRequestUtcTimestamp", "ClientResponseUtcTimestamp", "ForwardedRequestUtcTimestamp", "ForwardedResponseUtcTimestamp", "RequestXML", "ResponseXML", "XmlBookingLogin", "Success", "ErrorMessage", "RequestProcessor", "RequestURL", "ErrorStackTrace", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.jactravel.monitoring.PlatformTypeProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
