// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueryProxyRequest.proto

package com.jactravel.monitoring;

/**
 * Protobuf enum {@code Jactravel.Monitoring.QueryType}
 */
public enum QueryType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UnknownSearch = 0;</code>
   */
  UnknownSearch(0, 0),
  /**
   * <code>IVectorSearch = 1;</code>
   */
  IVectorSearch(1, 1),
  /**
   * <code>TravelStudioSearch = 2;</code>
   */
  TravelStudioSearch(2, 2),
  /**
   * <code>IVectorBook = 3;</code>
   */
  IVectorBook(3, 3),
  /**
   * <code>IVectorPreBook = 4;</code>
   */
  IVectorPreBook(4, 4),
  /**
   * <code>IVectorCancellation = 5;</code>
   */
  IVectorCancellation(5, 5),
  /**
   * <code>CMI = 6;</code>
   */
  CMI(6, 6),
  ;

  /**
   * <code>UnknownSearch = 0;</code>
   */
  public static final int UnknownSearch_VALUE = 0;
  /**
   * <code>IVectorSearch = 1;</code>
   */
  public static final int IVectorSearch_VALUE = 1;
  /**
   * <code>TravelStudioSearch = 2;</code>
   */
  public static final int TravelStudioSearch_VALUE = 2;
  /**
   * <code>IVectorBook = 3;</code>
   */
  public static final int IVectorBook_VALUE = 3;
  /**
   * <code>IVectorPreBook = 4;</code>
   */
  public static final int IVectorPreBook_VALUE = 4;
  /**
   * <code>IVectorCancellation = 5;</code>
   */
  public static final int IVectorCancellation_VALUE = 5;
  /**
   * <code>CMI = 6;</code>
   */
  public static final int CMI_VALUE = 6;


  public final int getNumber() { return value; }

  public static QueryType valueOf(int value) {
    switch (value) {
      case 0: return UnknownSearch;
      case 1: return IVectorSearch;
      case 2: return TravelStudioSearch;
      case 3: return IVectorBook;
      case 4: return IVectorPreBook;
      case 5: return IVectorCancellation;
      case 6: return CMI;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<QueryType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<QueryType>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<QueryType>() {
          public QueryType findValueByNumber(int number) {
            return QueryType.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.jactravel.monitoring.QueryProxyRequestProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final QueryType[] VALUES = values();

  public static QueryType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private QueryType(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Jactravel.Monitoring.QueryType)
}

