// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchReport.proto

package com.jactravel.monitoring;

public interface RoomRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 adults = 1;
  /**
   * <code>optional int32 adults = 1;</code>
   */
  boolean hasAdults();
  /**
   * <code>optional int32 adults = 1;</code>
   */
  int getAdults();

  // optional int32 children = 2;
  /**
   * <code>optional int32 children = 2;</code>
   */
  boolean hasChildren();
  /**
   * <code>optional int32 children = 2;</code>
   */
  int getChildren();

  // repeated int32 childAges = 3;
  /**
   * <code>repeated int32 childAges = 3;</code>
   */
  java.util.List<java.lang.Integer> getChildAgesList();
  /**
   * <code>repeated int32 childAges = 3;</code>
   */
  int getChildAgesCount();
  /**
   * <code>repeated int32 childAges = 3;</code>
   */
  int getChildAges(int index);
}
