// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchRequest.proto

package com.jactravel.monitoring;

/**
 * Protobuf type {@code Jactravel.Monitoring.RoomRequest}
 */
public  final class RoomRequest extends
    com.google.protobuf.GeneratedMessage
    implements RoomRequestOrBuilder {
  // Use RoomRequest.newBuilder() to construct.
  private RoomRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private RoomRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final RoomRequest defaultInstance;
  public static RoomRequest getDefaultInstance() {
    return defaultInstance;
  }

  public RoomRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private RoomRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            adults_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            children_ = input.readInt32();
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              childAges_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            childAges_.add(input.readInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              childAges_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              childAges_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        childAges_ = java.util.Collections.unmodifiableList(childAges_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jactravel.monitoring.SearchRequestProto.internal_static_Jactravel_Monitoring_RoomRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jactravel.monitoring.SearchRequestProto.internal_static_Jactravel_Monitoring_RoomRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jactravel.monitoring.RoomRequest.class, com.jactravel.monitoring.RoomRequest.Builder.class);
  }

  public static com.google.protobuf.Parser<RoomRequest> PARSER =
      new com.google.protobuf.AbstractParser<RoomRequest>() {
    public RoomRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RoomRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<RoomRequest> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional int32 adults = 1;
  public static final int ADULTS_FIELD_NUMBER = 1;
  private int adults_;
  /**
   * <code>optional int32 adults = 1;</code>
   */
  public boolean hasAdults() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int32 adults = 1;</code>
   */
  public int getAdults() {
    return adults_;
  }

  // optional int32 children = 2;
  public static final int CHILDREN_FIELD_NUMBER = 2;
  private int children_;
  /**
   * <code>optional int32 children = 2;</code>
   */
  public boolean hasChildren() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int32 children = 2;</code>
   */
  public int getChildren() {
    return children_;
  }

  // repeated int32 childAges = 3;
  public static final int CHILDAGES_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Integer> childAges_;
  /**
   * <code>repeated int32 childAges = 3;</code>
   */
  public java.util.List<java.lang.Integer>
      getChildAgesList() {
    return childAges_;
  }
  /**
   * <code>repeated int32 childAges = 3;</code>
   */
  public int getChildAgesCount() {
    return childAges_.size();
  }
  /**
   * <code>repeated int32 childAges = 3;</code>
   */
  public int getChildAges(int index) {
    return childAges_.get(index);
  }

  private void initFields() {
    adults_ = 0;
    children_ = 0;
    childAges_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, adults_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, children_);
    }
    for (int i = 0; i < childAges_.size(); i++) {
      output.writeInt32(3, childAges_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, adults_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, children_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < childAges_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(childAges_.get(i));
      }
      size += dataSize;
      size += 1 * getChildAgesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.jactravel.monitoring.RoomRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jactravel.monitoring.RoomRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jactravel.monitoring.RoomRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jactravel.monitoring.RoomRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jactravel.monitoring.RoomRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.jactravel.monitoring.RoomRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.jactravel.monitoring.RoomRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.jactravel.monitoring.RoomRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.jactravel.monitoring.RoomRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.jactravel.monitoring.RoomRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.jactravel.monitoring.RoomRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Jactravel.Monitoring.RoomRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.jactravel.monitoring.RoomRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jactravel.monitoring.SearchRequestProto.internal_static_Jactravel_Monitoring_RoomRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jactravel.monitoring.SearchRequestProto.internal_static_Jactravel_Monitoring_RoomRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jactravel.monitoring.RoomRequest.class, com.jactravel.monitoring.RoomRequest.Builder.class);
    }

    // Construct using com.jactravel.monitoring.RoomRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      adults_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      children_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      childAges_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jactravel.monitoring.SearchRequestProto.internal_static_Jactravel_Monitoring_RoomRequest_descriptor;
    }

    public com.jactravel.monitoring.RoomRequest getDefaultInstanceForType() {
      return com.jactravel.monitoring.RoomRequest.getDefaultInstance();
    }

    public com.jactravel.monitoring.RoomRequest build() {
      com.jactravel.monitoring.RoomRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jactravel.monitoring.RoomRequest buildPartial() {
      com.jactravel.monitoring.RoomRequest result = new com.jactravel.monitoring.RoomRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.adults_ = adults_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.children_ = children_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        childAges_ = java.util.Collections.unmodifiableList(childAges_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.childAges_ = childAges_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jactravel.monitoring.RoomRequest) {
        return mergeFrom((com.jactravel.monitoring.RoomRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jactravel.monitoring.RoomRequest other) {
      if (other == com.jactravel.monitoring.RoomRequest.getDefaultInstance()) return this;
      if (other.hasAdults()) {
        setAdults(other.getAdults());
      }
      if (other.hasChildren()) {
        setChildren(other.getChildren());
      }
      if (!other.childAges_.isEmpty()) {
        if (childAges_.isEmpty()) {
          childAges_ = other.childAges_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureChildAgesIsMutable();
          childAges_.addAll(other.childAges_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jactravel.monitoring.RoomRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jactravel.monitoring.RoomRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional int32 adults = 1;
    private int adults_ ;
    /**
     * <code>optional int32 adults = 1;</code>
     */
    public boolean hasAdults() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 adults = 1;</code>
     */
    public int getAdults() {
      return adults_;
    }
    /**
     * <code>optional int32 adults = 1;</code>
     */
    public Builder setAdults(int value) {
      bitField0_ |= 0x00000001;
      adults_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 adults = 1;</code>
     */
    public Builder clearAdults() {
      bitField0_ = (bitField0_ & ~0x00000001);
      adults_ = 0;
      onChanged();
      return this;
    }

    // optional int32 children = 2;
    private int children_ ;
    /**
     * <code>optional int32 children = 2;</code>
     */
    public boolean hasChildren() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 children = 2;</code>
     */
    public int getChildren() {
      return children_;
    }
    /**
     * <code>optional int32 children = 2;</code>
     */
    public Builder setChildren(int value) {
      bitField0_ |= 0x00000002;
      children_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 children = 2;</code>
     */
    public Builder clearChildren() {
      bitField0_ = (bitField0_ & ~0x00000002);
      children_ = 0;
      onChanged();
      return this;
    }

    // repeated int32 childAges = 3;
    private java.util.List<java.lang.Integer> childAges_ = java.util.Collections.emptyList();
    private void ensureChildAgesIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        childAges_ = new java.util.ArrayList<java.lang.Integer>(childAges_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int32 childAges = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getChildAgesList() {
      return java.util.Collections.unmodifiableList(childAges_);
    }
    /**
     * <code>repeated int32 childAges = 3;</code>
     */
    public int getChildAgesCount() {
      return childAges_.size();
    }
    /**
     * <code>repeated int32 childAges = 3;</code>
     */
    public int getChildAges(int index) {
      return childAges_.get(index);
    }
    /**
     * <code>repeated int32 childAges = 3;</code>
     */
    public Builder setChildAges(
        int index, int value) {
      ensureChildAgesIsMutable();
      childAges_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 childAges = 3;</code>
     */
    public Builder addChildAges(int value) {
      ensureChildAgesIsMutable();
      childAges_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 childAges = 3;</code>
     */
    public Builder addAllChildAges(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureChildAgesIsMutable();
      super.addAll(values, childAges_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 childAges = 3;</code>
     */
    public Builder clearChildAges() {
      childAges_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Jactravel.Monitoring.RoomRequest)
  }

  static {
    defaultInstance = new RoomRequest(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Jactravel.Monitoring.RoomRequest)
}

