// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchReport.proto

package com.jactravel.monitoring;

public interface SearchResponseInfoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 propertyReferenceCount = 1;
  /**
   * <code>optional int32 propertyReferenceCount = 1;</code>
   *
   * <pre>
   * total number of unique Properties retunred in a search (same as TotalProperties in search response xml)
   * </pre>
   */
  boolean hasPropertyReferenceCount();
  /**
   * <code>optional int32 propertyReferenceCount = 1;</code>
   *
   * <pre>
   * total number of unique Properties retunred in a search (same as TotalProperties in search response xml)
   * </pre>
   */
  int getPropertyReferenceCount();

  // optional int32 propertyCount = 2;
  /**
   * <code>optional int32 propertyCount = 2;</code>
   *
   * <pre>
   * total number of unique Properties processed for the search. (i.e. Property Count before the deduplication process)
   * </pre>
   */
  boolean hasPropertyCount();
  /**
   * <code>optional int32 propertyCount = 2;</code>
   *
   * <pre>
   * total number of unique Properties processed for the search. (i.e. Property Count before the deduplication process)
   * </pre>
   */
  int getPropertyCount();

  // optional int32 pricedRoomCount = 3;
  /**
   * <code>optional int32 pricedRoomCount = 3;</code>
   */
  boolean hasPricedRoomCount();
  /**
   * <code>optional int32 pricedRoomCount = 3;</code>
   */
  int getPricedRoomCount();

  // repeated string suppliersSearched = 4;
  /**
   * <code>repeated string suppliersSearched = 4;</code>
   */
  java.util.List<java.lang.String>
  getSuppliersSearchedList();
  /**
   * <code>repeated string suppliersSearched = 4;</code>
   */
  int getSuppliersSearchedCount();
  /**
   * <code>repeated string suppliersSearched = 4;</code>
   */
  java.lang.String getSuppliersSearched(int index);
  /**
   * <code>repeated string suppliersSearched = 4;</code>
   */
  com.google.protobuf.ByteString
      getSuppliersSearchedBytes(int index);

  // optional string success = 5;
  /**
   * <code>optional string success = 5;</code>
   */
  boolean hasSuccess();
  /**
   * <code>optional string success = 5;</code>
   */
  java.lang.String getSuccess();
  /**
   * <code>optional string success = 5;</code>
   */
  com.google.protobuf.ByteString
      getSuccessBytes();

  // optional string errorMessage = 6;
  /**
   * <code>optional string errorMessage = 6;</code>
   */
  boolean hasErrorMessage();
  /**
   * <code>optional string errorMessage = 6;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>optional string errorMessage = 6;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  // optional string errorStackTrace = 7;
  /**
   * <code>optional string errorStackTrace = 7;</code>
   */
  boolean hasErrorStackTrace();
  /**
   * <code>optional string errorStackTrace = 7;</code>
   */
  java.lang.String getErrorStackTrace();
  /**
   * <code>optional string errorStackTrace = 7;</code>
   */
  com.google.protobuf.ByteString
      getErrorStackTraceBytes();
}
