// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchRequest.proto

package com.jactravel.monitoring;

/**
 * Protobuf type {@code Jactravel.Monitoring.SearchRequestInfo}
 */
public  final class SearchRequestInfo extends
    com.google.protobuf.GeneratedMessage
    implements SearchRequestInfoOrBuilder {
  // Use SearchRequestInfo.newBuilder() to construct.
  private SearchRequestInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private SearchRequestInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final SearchRequestInfo defaultInstance;
  public static SearchRequestInfo getDefaultInstance() {
    return defaultInstance;
  }

  public SearchRequestInfo getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private SearchRequestInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            startUtcTimestamp_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            endUtcTimestamp_ = input.readBytes();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            tradeID_ = input.readInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            brandID_ = input.readInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            salesChannelID_ = input.readInt32();
            break;
          }
          case 48: {
            int rawValue = input.readEnum();
            com.jactravel.monitoring.GeoLevel value = com.jactravel.monitoring.GeoLevel.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(6, rawValue);
            } else {
              bitField0_ |= 0x00000020;
              searchGeoLevel_ = value;
            }
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            geoLevel1ID_ = input.readInt32();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000080;
            geoLevel2ID_ = input.readInt32();
            break;
          }
          case 72: {
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              geoLevel3IDs_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000100;
            }
            geoLevel3IDs_.add(input.readInt32());
            break;
          }
          case 74: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100) && input.getBytesUntilLimit() > 0) {
              geoLevel3IDs_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000100;
            }
            while (input.getBytesUntilLimit() > 0) {
              geoLevel3IDs_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 80: {
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              propertyReferenceIDs_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000200;
            }
            propertyReferenceIDs_.add(input.readInt32());
            break;
          }
          case 82: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200) && input.getBytesUntilLimit() > 0) {
              propertyReferenceIDs_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000200;
            }
            while (input.getBytesUntilLimit() > 0) {
              propertyReferenceIDs_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 88: {
            if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
              propertyIDs_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000400;
            }
            propertyIDs_.add(input.readInt32());
            break;
          }
          case 90: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000400) == 0x00000400) && input.getBytesUntilLimit() > 0) {
              propertyIDs_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000400;
            }
            while (input.getBytesUntilLimit() > 0) {
              propertyIDs_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 98: {
            bitField0_ |= 0x00000100;
            minStarRating_ = input.readBytes();
            break;
          }
          case 106: {
            bitField0_ |= 0x00000200;
            arrivalDate_ = input.readBytes();
            break;
          }
          case 112: {
            bitField0_ |= 0x00000400;
            duration_ = input.readInt32();
            break;
          }
          case 120: {
            bitField0_ |= 0x00000800;
            mealBasisID_ = input.readInt32();
            break;
          }
          case 130: {
            if (!((mutable_bitField0_ & 0x00008000) == 0x00008000)) {
              rooms_ = new java.util.ArrayList<com.jactravel.monitoring.RoomRequest>();
              mutable_bitField0_ |= 0x00008000;
            }
            rooms_.add(input.readMessage(com.jactravel.monitoring.RoomRequest.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        geoLevel3IDs_ = java.util.Collections.unmodifiableList(geoLevel3IDs_);
      }
      if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
        propertyReferenceIDs_ = java.util.Collections.unmodifiableList(propertyReferenceIDs_);
      }
      if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
        propertyIDs_ = java.util.Collections.unmodifiableList(propertyIDs_);
      }
      if (((mutable_bitField0_ & 0x00008000) == 0x00008000)) {
        rooms_ = java.util.Collections.unmodifiableList(rooms_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jactravel.monitoring.SearchRequestProto.internal_static_Jactravel_Monitoring_SearchRequestInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jactravel.monitoring.SearchRequestProto.internal_static_Jactravel_Monitoring_SearchRequestInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jactravel.monitoring.SearchRequestInfo.class, com.jactravel.monitoring.SearchRequestInfo.Builder.class);
  }

  public static com.google.protobuf.Parser<SearchRequestInfo> PARSER =
      new com.google.protobuf.AbstractParser<SearchRequestInfo>() {
    public SearchRequestInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchRequestInfo(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<SearchRequestInfo> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional string startUtcTimestamp = 1;
  public static final int STARTUTCTIMESTAMP_FIELD_NUMBER = 1;
  private java.lang.Object startUtcTimestamp_;
  /**
   * <code>optional string startUtcTimestamp = 1;</code>
   */
  public boolean hasStartUtcTimestamp() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string startUtcTimestamp = 1;</code>
   */
  public java.lang.String getStartUtcTimestamp() {
    java.lang.Object ref = startUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        startUtcTimestamp_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string startUtcTimestamp = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStartUtcTimestampBytes() {
    java.lang.Object ref = startUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startUtcTimestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string endUtcTimestamp = 2;
  public static final int ENDUTCTIMESTAMP_FIELD_NUMBER = 2;
  private java.lang.Object endUtcTimestamp_;
  /**
   * <code>optional string endUtcTimestamp = 2;</code>
   */
  public boolean hasEndUtcTimestamp() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string endUtcTimestamp = 2;</code>
   */
  public java.lang.String getEndUtcTimestamp() {
    java.lang.Object ref = endUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        endUtcTimestamp_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string endUtcTimestamp = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEndUtcTimestampBytes() {
    java.lang.Object ref = endUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endUtcTimestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int32 tradeID = 3;
  public static final int TRADEID_FIELD_NUMBER = 3;
  private int tradeID_;
  /**
   * <code>optional int32 tradeID = 3;</code>
   */
  public boolean hasTradeID() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int32 tradeID = 3;</code>
   */
  public int getTradeID() {
    return tradeID_;
  }

  // optional int32 brandID = 4;
  public static final int BRANDID_FIELD_NUMBER = 4;
  private int brandID_;
  /**
   * <code>optional int32 brandID = 4;</code>
   */
  public boolean hasBrandID() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int32 brandID = 4;</code>
   */
  public int getBrandID() {
    return brandID_;
  }

  // optional int32 salesChannelID = 5;
  public static final int SALESCHANNELID_FIELD_NUMBER = 5;
  private int salesChannelID_;
  /**
   * <code>optional int32 salesChannelID = 5;</code>
   */
  public boolean hasSalesChannelID() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional int32 salesChannelID = 5;</code>
   */
  public int getSalesChannelID() {
    return salesChannelID_;
  }

  // optional .Jactravel.Monitoring.GeoLevel searchGeoLevel = 6;
  public static final int SEARCHGEOLEVEL_FIELD_NUMBER = 6;
  private com.jactravel.monitoring.GeoLevel searchGeoLevel_;
  /**
   * <code>optional .Jactravel.Monitoring.GeoLevel searchGeoLevel = 6;</code>
   */
  public boolean hasSearchGeoLevel() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional .Jactravel.Monitoring.GeoLevel searchGeoLevel = 6;</code>
   */
  public com.jactravel.monitoring.GeoLevel getSearchGeoLevel() {
    return searchGeoLevel_;
  }

  // optional int32 geoLevel1ID = 7;
  public static final int GEOLEVEL1ID_FIELD_NUMBER = 7;
  private int geoLevel1ID_;
  /**
   * <code>optional int32 geoLevel1ID = 7;</code>
   */
  public boolean hasGeoLevel1ID() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional int32 geoLevel1ID = 7;</code>
   */
  public int getGeoLevel1ID() {
    return geoLevel1ID_;
  }

  // optional int32 geoLevel2ID = 8;
  public static final int GEOLEVEL2ID_FIELD_NUMBER = 8;
  private int geoLevel2ID_;
  /**
   * <code>optional int32 geoLevel2ID = 8;</code>
   */
  public boolean hasGeoLevel2ID() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional int32 geoLevel2ID = 8;</code>
   */
  public int getGeoLevel2ID() {
    return geoLevel2ID_;
  }

  // repeated int32 geoLevel3IDs = 9;
  public static final int GEOLEVEL3IDS_FIELD_NUMBER = 9;
  private java.util.List<java.lang.Integer> geoLevel3IDs_;
  /**
   * <code>repeated int32 geoLevel3IDs = 9;</code>
   */
  public java.util.List<java.lang.Integer>
      getGeoLevel3IDsList() {
    return geoLevel3IDs_;
  }
  /**
   * <code>repeated int32 geoLevel3IDs = 9;</code>
   */
  public int getGeoLevel3IDsCount() {
    return geoLevel3IDs_.size();
  }
  /**
   * <code>repeated int32 geoLevel3IDs = 9;</code>
   */
  public int getGeoLevel3IDs(int index) {
    return geoLevel3IDs_.get(index);
  }

  // repeated int32 propertyReferenceIDs = 10;
  public static final int PROPERTYREFERENCEIDS_FIELD_NUMBER = 10;
  private java.util.List<java.lang.Integer> propertyReferenceIDs_;
  /**
   * <code>repeated int32 propertyReferenceIDs = 10;</code>
   */
  public java.util.List<java.lang.Integer>
      getPropertyReferenceIDsList() {
    return propertyReferenceIDs_;
  }
  /**
   * <code>repeated int32 propertyReferenceIDs = 10;</code>
   */
  public int getPropertyReferenceIDsCount() {
    return propertyReferenceIDs_.size();
  }
  /**
   * <code>repeated int32 propertyReferenceIDs = 10;</code>
   */
  public int getPropertyReferenceIDs(int index) {
    return propertyReferenceIDs_.get(index);
  }

  // repeated int32 propertyIDs = 11;
  public static final int PROPERTYIDS_FIELD_NUMBER = 11;
  private java.util.List<java.lang.Integer> propertyIDs_;
  /**
   * <code>repeated int32 propertyIDs = 11;</code>
   */
  public java.util.List<java.lang.Integer>
      getPropertyIDsList() {
    return propertyIDs_;
  }
  /**
   * <code>repeated int32 propertyIDs = 11;</code>
   */
  public int getPropertyIDsCount() {
    return propertyIDs_.size();
  }
  /**
   * <code>repeated int32 propertyIDs = 11;</code>
   */
  public int getPropertyIDs(int index) {
    return propertyIDs_.get(index);
  }

  // optional string minStarRating = 12;
  public static final int MINSTARRATING_FIELD_NUMBER = 12;
  private java.lang.Object minStarRating_;
  /**
   * <code>optional string minStarRating = 12;</code>
   */
  public boolean hasMinStarRating() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional string minStarRating = 12;</code>
   */
  public java.lang.String getMinStarRating() {
    java.lang.Object ref = minStarRating_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        minStarRating_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string minStarRating = 12;</code>
   */
  public com.google.protobuf.ByteString
      getMinStarRatingBytes() {
    java.lang.Object ref = minStarRating_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      minStarRating_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string arrivalDate = 13;
  public static final int ARRIVALDATE_FIELD_NUMBER = 13;
  private java.lang.Object arrivalDate_;
  /**
   * <code>optional string arrivalDate = 13;</code>
   */
  public boolean hasArrivalDate() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional string arrivalDate = 13;</code>
   */
  public java.lang.String getArrivalDate() {
    java.lang.Object ref = arrivalDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        arrivalDate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string arrivalDate = 13;</code>
   */
  public com.google.protobuf.ByteString
      getArrivalDateBytes() {
    java.lang.Object ref = arrivalDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arrivalDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int32 duration = 14;
  public static final int DURATION_FIELD_NUMBER = 14;
  private int duration_;
  /**
   * <code>optional int32 duration = 14;</code>
   */
  public boolean hasDuration() {
    return ((bitField0_ & 0x00000400) == 0x00000400);
  }
  /**
   * <code>optional int32 duration = 14;</code>
   */
  public int getDuration() {
    return duration_;
  }

  // optional int32 mealBasisID = 15;
  public static final int MEALBASISID_FIELD_NUMBER = 15;
  private int mealBasisID_;
  /**
   * <code>optional int32 mealBasisID = 15;</code>
   */
  public boolean hasMealBasisID() {
    return ((bitField0_ & 0x00000800) == 0x00000800);
  }
  /**
   * <code>optional int32 mealBasisID = 15;</code>
   */
  public int getMealBasisID() {
    return mealBasisID_;
  }

  // repeated .Jactravel.Monitoring.RoomRequest rooms = 16;
  public static final int ROOMS_FIELD_NUMBER = 16;
  private java.util.List<com.jactravel.monitoring.RoomRequest> rooms_;
  /**
   * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
   */
  public java.util.List<com.jactravel.monitoring.RoomRequest> getRoomsList() {
    return rooms_;
  }
  /**
   * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
   */
  public java.util.List<? extends com.jactravel.monitoring.RoomRequestOrBuilder> 
      getRoomsOrBuilderList() {
    return rooms_;
  }
  /**
   * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
   */
  public int getRoomsCount() {
    return rooms_.size();
  }
  /**
   * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
   */
  public com.jactravel.monitoring.RoomRequest getRooms(int index) {
    return rooms_.get(index);
  }
  /**
   * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
   */
  public com.jactravel.monitoring.RoomRequestOrBuilder getRoomsOrBuilder(
      int index) {
    return rooms_.get(index);
  }

  private void initFields() {
    startUtcTimestamp_ = "";
    endUtcTimestamp_ = "";
    tradeID_ = 0;
    brandID_ = 0;
    salesChannelID_ = 0;
    searchGeoLevel_ = com.jactravel.monitoring.GeoLevel.UnknownGeoLevel;
    geoLevel1ID_ = 0;
    geoLevel2ID_ = 0;
    geoLevel3IDs_ = java.util.Collections.emptyList();
    propertyReferenceIDs_ = java.util.Collections.emptyList();
    propertyIDs_ = java.util.Collections.emptyList();
    minStarRating_ = "";
    arrivalDate_ = "";
    duration_ = 0;
    mealBasisID_ = 0;
    rooms_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getStartUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getEndUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, tradeID_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, brandID_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt32(5, salesChannelID_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeEnum(6, searchGeoLevel_.getNumber());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeInt32(7, geoLevel1ID_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeInt32(8, geoLevel2ID_);
    }
    for (int i = 0; i < geoLevel3IDs_.size(); i++) {
      output.writeInt32(9, geoLevel3IDs_.get(i));
    }
    for (int i = 0; i < propertyReferenceIDs_.size(); i++) {
      output.writeInt32(10, propertyReferenceIDs_.get(i));
    }
    for (int i = 0; i < propertyIDs_.size(); i++) {
      output.writeInt32(11, propertyIDs_.get(i));
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeBytes(12, getMinStarRatingBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeBytes(13, getArrivalDateBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      output.writeInt32(14, duration_);
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      output.writeInt32(15, mealBasisID_);
    }
    for (int i = 0; i < rooms_.size(); i++) {
      output.writeMessage(16, rooms_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getStartUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getEndUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, tradeID_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, brandID_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, salesChannelID_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, searchGeoLevel_.getNumber());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, geoLevel1ID_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, geoLevel2ID_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < geoLevel3IDs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(geoLevel3IDs_.get(i));
      }
      size += dataSize;
      size += 1 * getGeoLevel3IDsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < propertyReferenceIDs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(propertyReferenceIDs_.get(i));
      }
      size += dataSize;
      size += 1 * getPropertyReferenceIDsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < propertyIDs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(propertyIDs_.get(i));
      }
      size += dataSize;
      size += 1 * getPropertyIDsList().size();
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, getMinStarRatingBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(13, getArrivalDateBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, duration_);
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, mealBasisID_);
    }
    for (int i = 0; i < rooms_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, rooms_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.jactravel.monitoring.SearchRequestInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jactravel.monitoring.SearchRequestInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jactravel.monitoring.SearchRequestInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jactravel.monitoring.SearchRequestInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jactravel.monitoring.SearchRequestInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.jactravel.monitoring.SearchRequestInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.jactravel.monitoring.SearchRequestInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.jactravel.monitoring.SearchRequestInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.jactravel.monitoring.SearchRequestInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.jactravel.monitoring.SearchRequestInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.jactravel.monitoring.SearchRequestInfo prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Jactravel.Monitoring.SearchRequestInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.jactravel.monitoring.SearchRequestInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jactravel.monitoring.SearchRequestProto.internal_static_Jactravel_Monitoring_SearchRequestInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jactravel.monitoring.SearchRequestProto.internal_static_Jactravel_Monitoring_SearchRequestInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jactravel.monitoring.SearchRequestInfo.class, com.jactravel.monitoring.SearchRequestInfo.Builder.class);
    }

    // Construct using com.jactravel.monitoring.SearchRequestInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getRoomsFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      startUtcTimestamp_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      endUtcTimestamp_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      tradeID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      brandID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      salesChannelID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      searchGeoLevel_ = com.jactravel.monitoring.GeoLevel.UnknownGeoLevel;
      bitField0_ = (bitField0_ & ~0x00000020);
      geoLevel1ID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000040);
      geoLevel2ID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      geoLevel3IDs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000100);
      propertyReferenceIDs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000200);
      propertyIDs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000400);
      minStarRating_ = "";
      bitField0_ = (bitField0_ & ~0x00000800);
      arrivalDate_ = "";
      bitField0_ = (bitField0_ & ~0x00001000);
      duration_ = 0;
      bitField0_ = (bitField0_ & ~0x00002000);
      mealBasisID_ = 0;
      bitField0_ = (bitField0_ & ~0x00004000);
      if (roomsBuilder_ == null) {
        rooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00008000);
      } else {
        roomsBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jactravel.monitoring.SearchRequestProto.internal_static_Jactravel_Monitoring_SearchRequestInfo_descriptor;
    }

    public com.jactravel.monitoring.SearchRequestInfo getDefaultInstanceForType() {
      return com.jactravel.monitoring.SearchRequestInfo.getDefaultInstance();
    }

    public com.jactravel.monitoring.SearchRequestInfo build() {
      com.jactravel.monitoring.SearchRequestInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jactravel.monitoring.SearchRequestInfo buildPartial() {
      com.jactravel.monitoring.SearchRequestInfo result = new com.jactravel.monitoring.SearchRequestInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.startUtcTimestamp_ = startUtcTimestamp_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.endUtcTimestamp_ = endUtcTimestamp_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.tradeID_ = tradeID_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.brandID_ = brandID_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.salesChannelID_ = salesChannelID_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.searchGeoLevel_ = searchGeoLevel_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.geoLevel1ID_ = geoLevel1ID_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.geoLevel2ID_ = geoLevel2ID_;
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        geoLevel3IDs_ = java.util.Collections.unmodifiableList(geoLevel3IDs_);
        bitField0_ = (bitField0_ & ~0x00000100);
      }
      result.geoLevel3IDs_ = geoLevel3IDs_;
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        propertyReferenceIDs_ = java.util.Collections.unmodifiableList(propertyReferenceIDs_);
        bitField0_ = (bitField0_ & ~0x00000200);
      }
      result.propertyReferenceIDs_ = propertyReferenceIDs_;
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        propertyIDs_ = java.util.Collections.unmodifiableList(propertyIDs_);
        bitField0_ = (bitField0_ & ~0x00000400);
      }
      result.propertyIDs_ = propertyIDs_;
      if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
        to_bitField0_ |= 0x00000100;
      }
      result.minStarRating_ = minStarRating_;
      if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
        to_bitField0_ |= 0x00000200;
      }
      result.arrivalDate_ = arrivalDate_;
      if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
        to_bitField0_ |= 0x00000400;
      }
      result.duration_ = duration_;
      if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
        to_bitField0_ |= 0x00000800;
      }
      result.mealBasisID_ = mealBasisID_;
      if (roomsBuilder_ == null) {
        if (((bitField0_ & 0x00008000) == 0x00008000)) {
          rooms_ = java.util.Collections.unmodifiableList(rooms_);
          bitField0_ = (bitField0_ & ~0x00008000);
        }
        result.rooms_ = rooms_;
      } else {
        result.rooms_ = roomsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jactravel.monitoring.SearchRequestInfo) {
        return mergeFrom((com.jactravel.monitoring.SearchRequestInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jactravel.monitoring.SearchRequestInfo other) {
      if (other == com.jactravel.monitoring.SearchRequestInfo.getDefaultInstance()) return this;
      if (other.hasStartUtcTimestamp()) {
        bitField0_ |= 0x00000001;
        startUtcTimestamp_ = other.startUtcTimestamp_;
        onChanged();
      }
      if (other.hasEndUtcTimestamp()) {
        bitField0_ |= 0x00000002;
        endUtcTimestamp_ = other.endUtcTimestamp_;
        onChanged();
      }
      if (other.hasTradeID()) {
        setTradeID(other.getTradeID());
      }
      if (other.hasBrandID()) {
        setBrandID(other.getBrandID());
      }
      if (other.hasSalesChannelID()) {
        setSalesChannelID(other.getSalesChannelID());
      }
      if (other.hasSearchGeoLevel()) {
        setSearchGeoLevel(other.getSearchGeoLevel());
      }
      if (other.hasGeoLevel1ID()) {
        setGeoLevel1ID(other.getGeoLevel1ID());
      }
      if (other.hasGeoLevel2ID()) {
        setGeoLevel2ID(other.getGeoLevel2ID());
      }
      if (!other.geoLevel3IDs_.isEmpty()) {
        if (geoLevel3IDs_.isEmpty()) {
          geoLevel3IDs_ = other.geoLevel3IDs_;
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          ensureGeoLevel3IDsIsMutable();
          geoLevel3IDs_.addAll(other.geoLevel3IDs_);
        }
        onChanged();
      }
      if (!other.propertyReferenceIDs_.isEmpty()) {
        if (propertyReferenceIDs_.isEmpty()) {
          propertyReferenceIDs_ = other.propertyReferenceIDs_;
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          ensurePropertyReferenceIDsIsMutable();
          propertyReferenceIDs_.addAll(other.propertyReferenceIDs_);
        }
        onChanged();
      }
      if (!other.propertyIDs_.isEmpty()) {
        if (propertyIDs_.isEmpty()) {
          propertyIDs_ = other.propertyIDs_;
          bitField0_ = (bitField0_ & ~0x00000400);
        } else {
          ensurePropertyIDsIsMutable();
          propertyIDs_.addAll(other.propertyIDs_);
        }
        onChanged();
      }
      if (other.hasMinStarRating()) {
        bitField0_ |= 0x00000800;
        minStarRating_ = other.minStarRating_;
        onChanged();
      }
      if (other.hasArrivalDate()) {
        bitField0_ |= 0x00001000;
        arrivalDate_ = other.arrivalDate_;
        onChanged();
      }
      if (other.hasDuration()) {
        setDuration(other.getDuration());
      }
      if (other.hasMealBasisID()) {
        setMealBasisID(other.getMealBasisID());
      }
      if (roomsBuilder_ == null) {
        if (!other.rooms_.isEmpty()) {
          if (rooms_.isEmpty()) {
            rooms_ = other.rooms_;
            bitField0_ = (bitField0_ & ~0x00008000);
          } else {
            ensureRoomsIsMutable();
            rooms_.addAll(other.rooms_);
          }
          onChanged();
        }
      } else {
        if (!other.rooms_.isEmpty()) {
          if (roomsBuilder_.isEmpty()) {
            roomsBuilder_.dispose();
            roomsBuilder_ = null;
            rooms_ = other.rooms_;
            bitField0_ = (bitField0_ & ~0x00008000);
            roomsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getRoomsFieldBuilder() : null;
          } else {
            roomsBuilder_.addAllMessages(other.rooms_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jactravel.monitoring.SearchRequestInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jactravel.monitoring.SearchRequestInfo) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string startUtcTimestamp = 1;
    private java.lang.Object startUtcTimestamp_ = "";
    /**
     * <code>optional string startUtcTimestamp = 1;</code>
     */
    public boolean hasStartUtcTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string startUtcTimestamp = 1;</code>
     */
    public java.lang.String getStartUtcTimestamp() {
      java.lang.Object ref = startUtcTimestamp_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        startUtcTimestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string startUtcTimestamp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStartUtcTimestampBytes() {
      java.lang.Object ref = startUtcTimestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startUtcTimestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string startUtcTimestamp = 1;</code>
     */
    public Builder setStartUtcTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      startUtcTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string startUtcTimestamp = 1;</code>
     */
    public Builder clearStartUtcTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      startUtcTimestamp_ = getDefaultInstance().getStartUtcTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string startUtcTimestamp = 1;</code>
     */
    public Builder setStartUtcTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      startUtcTimestamp_ = value;
      onChanged();
      return this;
    }

    // optional string endUtcTimestamp = 2;
    private java.lang.Object endUtcTimestamp_ = "";
    /**
     * <code>optional string endUtcTimestamp = 2;</code>
     */
    public boolean hasEndUtcTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string endUtcTimestamp = 2;</code>
     */
    public java.lang.String getEndUtcTimestamp() {
      java.lang.Object ref = endUtcTimestamp_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        endUtcTimestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string endUtcTimestamp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEndUtcTimestampBytes() {
      java.lang.Object ref = endUtcTimestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endUtcTimestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string endUtcTimestamp = 2;</code>
     */
    public Builder setEndUtcTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      endUtcTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string endUtcTimestamp = 2;</code>
     */
    public Builder clearEndUtcTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      endUtcTimestamp_ = getDefaultInstance().getEndUtcTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string endUtcTimestamp = 2;</code>
     */
    public Builder setEndUtcTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      endUtcTimestamp_ = value;
      onChanged();
      return this;
    }

    // optional int32 tradeID = 3;
    private int tradeID_ ;
    /**
     * <code>optional int32 tradeID = 3;</code>
     */
    public boolean hasTradeID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 tradeID = 3;</code>
     */
    public int getTradeID() {
      return tradeID_;
    }
    /**
     * <code>optional int32 tradeID = 3;</code>
     */
    public Builder setTradeID(int value) {
      bitField0_ |= 0x00000004;
      tradeID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 tradeID = 3;</code>
     */
    public Builder clearTradeID() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tradeID_ = 0;
      onChanged();
      return this;
    }

    // optional int32 brandID = 4;
    private int brandID_ ;
    /**
     * <code>optional int32 brandID = 4;</code>
     */
    public boolean hasBrandID() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 brandID = 4;</code>
     */
    public int getBrandID() {
      return brandID_;
    }
    /**
     * <code>optional int32 brandID = 4;</code>
     */
    public Builder setBrandID(int value) {
      bitField0_ |= 0x00000008;
      brandID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 brandID = 4;</code>
     */
    public Builder clearBrandID() {
      bitField0_ = (bitField0_ & ~0x00000008);
      brandID_ = 0;
      onChanged();
      return this;
    }

    // optional int32 salesChannelID = 5;
    private int salesChannelID_ ;
    /**
     * <code>optional int32 salesChannelID = 5;</code>
     */
    public boolean hasSalesChannelID() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 salesChannelID = 5;</code>
     */
    public int getSalesChannelID() {
      return salesChannelID_;
    }
    /**
     * <code>optional int32 salesChannelID = 5;</code>
     */
    public Builder setSalesChannelID(int value) {
      bitField0_ |= 0x00000010;
      salesChannelID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 salesChannelID = 5;</code>
     */
    public Builder clearSalesChannelID() {
      bitField0_ = (bitField0_ & ~0x00000010);
      salesChannelID_ = 0;
      onChanged();
      return this;
    }

    // optional .Jactravel.Monitoring.GeoLevel searchGeoLevel = 6;
    private com.jactravel.monitoring.GeoLevel searchGeoLevel_ = com.jactravel.monitoring.GeoLevel.UnknownGeoLevel;
    /**
     * <code>optional .Jactravel.Monitoring.GeoLevel searchGeoLevel = 6;</code>
     */
    public boolean hasSearchGeoLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .Jactravel.Monitoring.GeoLevel searchGeoLevel = 6;</code>
     */
    public com.jactravel.monitoring.GeoLevel getSearchGeoLevel() {
      return searchGeoLevel_;
    }
    /**
     * <code>optional .Jactravel.Monitoring.GeoLevel searchGeoLevel = 6;</code>
     */
    public Builder setSearchGeoLevel(com.jactravel.monitoring.GeoLevel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      searchGeoLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Jactravel.Monitoring.GeoLevel searchGeoLevel = 6;</code>
     */
    public Builder clearSearchGeoLevel() {
      bitField0_ = (bitField0_ & ~0x00000020);
      searchGeoLevel_ = com.jactravel.monitoring.GeoLevel.UnknownGeoLevel;
      onChanged();
      return this;
    }

    // optional int32 geoLevel1ID = 7;
    private int geoLevel1ID_ ;
    /**
     * <code>optional int32 geoLevel1ID = 7;</code>
     */
    public boolean hasGeoLevel1ID() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 geoLevel1ID = 7;</code>
     */
    public int getGeoLevel1ID() {
      return geoLevel1ID_;
    }
    /**
     * <code>optional int32 geoLevel1ID = 7;</code>
     */
    public Builder setGeoLevel1ID(int value) {
      bitField0_ |= 0x00000040;
      geoLevel1ID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 geoLevel1ID = 7;</code>
     */
    public Builder clearGeoLevel1ID() {
      bitField0_ = (bitField0_ & ~0x00000040);
      geoLevel1ID_ = 0;
      onChanged();
      return this;
    }

    // optional int32 geoLevel2ID = 8;
    private int geoLevel2ID_ ;
    /**
     * <code>optional int32 geoLevel2ID = 8;</code>
     */
    public boolean hasGeoLevel2ID() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 geoLevel2ID = 8;</code>
     */
    public int getGeoLevel2ID() {
      return geoLevel2ID_;
    }
    /**
     * <code>optional int32 geoLevel2ID = 8;</code>
     */
    public Builder setGeoLevel2ID(int value) {
      bitField0_ |= 0x00000080;
      geoLevel2ID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 geoLevel2ID = 8;</code>
     */
    public Builder clearGeoLevel2ID() {
      bitField0_ = (bitField0_ & ~0x00000080);
      geoLevel2ID_ = 0;
      onChanged();
      return this;
    }

    // repeated int32 geoLevel3IDs = 9;
    private java.util.List<java.lang.Integer> geoLevel3IDs_ = java.util.Collections.emptyList();
    private void ensureGeoLevel3IDsIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        geoLevel3IDs_ = new java.util.ArrayList<java.lang.Integer>(geoLevel3IDs_);
        bitField0_ |= 0x00000100;
       }
    }
    /**
     * <code>repeated int32 geoLevel3IDs = 9;</code>
     */
    public java.util.List<java.lang.Integer>
        getGeoLevel3IDsList() {
      return java.util.Collections.unmodifiableList(geoLevel3IDs_);
    }
    /**
     * <code>repeated int32 geoLevel3IDs = 9;</code>
     */
    public int getGeoLevel3IDsCount() {
      return geoLevel3IDs_.size();
    }
    /**
     * <code>repeated int32 geoLevel3IDs = 9;</code>
     */
    public int getGeoLevel3IDs(int index) {
      return geoLevel3IDs_.get(index);
    }
    /**
     * <code>repeated int32 geoLevel3IDs = 9;</code>
     */
    public Builder setGeoLevel3IDs(
        int index, int value) {
      ensureGeoLevel3IDsIsMutable();
      geoLevel3IDs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 geoLevel3IDs = 9;</code>
     */
    public Builder addGeoLevel3IDs(int value) {
      ensureGeoLevel3IDsIsMutable();
      geoLevel3IDs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 geoLevel3IDs = 9;</code>
     */
    public Builder addAllGeoLevel3IDs(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureGeoLevel3IDsIsMutable();
      super.addAll(values, geoLevel3IDs_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 geoLevel3IDs = 9;</code>
     */
    public Builder clearGeoLevel3IDs() {
      geoLevel3IDs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }

    // repeated int32 propertyReferenceIDs = 10;
    private java.util.List<java.lang.Integer> propertyReferenceIDs_ = java.util.Collections.emptyList();
    private void ensurePropertyReferenceIDsIsMutable() {
      if (!((bitField0_ & 0x00000200) == 0x00000200)) {
        propertyReferenceIDs_ = new java.util.ArrayList<java.lang.Integer>(propertyReferenceIDs_);
        bitField0_ |= 0x00000200;
       }
    }
    /**
     * <code>repeated int32 propertyReferenceIDs = 10;</code>
     */
    public java.util.List<java.lang.Integer>
        getPropertyReferenceIDsList() {
      return java.util.Collections.unmodifiableList(propertyReferenceIDs_);
    }
    /**
     * <code>repeated int32 propertyReferenceIDs = 10;</code>
     */
    public int getPropertyReferenceIDsCount() {
      return propertyReferenceIDs_.size();
    }
    /**
     * <code>repeated int32 propertyReferenceIDs = 10;</code>
     */
    public int getPropertyReferenceIDs(int index) {
      return propertyReferenceIDs_.get(index);
    }
    /**
     * <code>repeated int32 propertyReferenceIDs = 10;</code>
     */
    public Builder setPropertyReferenceIDs(
        int index, int value) {
      ensurePropertyReferenceIDsIsMutable();
      propertyReferenceIDs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 propertyReferenceIDs = 10;</code>
     */
    public Builder addPropertyReferenceIDs(int value) {
      ensurePropertyReferenceIDsIsMutable();
      propertyReferenceIDs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 propertyReferenceIDs = 10;</code>
     */
    public Builder addAllPropertyReferenceIDs(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensurePropertyReferenceIDsIsMutable();
      super.addAll(values, propertyReferenceIDs_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 propertyReferenceIDs = 10;</code>
     */
    public Builder clearPropertyReferenceIDs() {
      propertyReferenceIDs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }

    // repeated int32 propertyIDs = 11;
    private java.util.List<java.lang.Integer> propertyIDs_ = java.util.Collections.emptyList();
    private void ensurePropertyIDsIsMutable() {
      if (!((bitField0_ & 0x00000400) == 0x00000400)) {
        propertyIDs_ = new java.util.ArrayList<java.lang.Integer>(propertyIDs_);
        bitField0_ |= 0x00000400;
       }
    }
    /**
     * <code>repeated int32 propertyIDs = 11;</code>
     */
    public java.util.List<java.lang.Integer>
        getPropertyIDsList() {
      return java.util.Collections.unmodifiableList(propertyIDs_);
    }
    /**
     * <code>repeated int32 propertyIDs = 11;</code>
     */
    public int getPropertyIDsCount() {
      return propertyIDs_.size();
    }
    /**
     * <code>repeated int32 propertyIDs = 11;</code>
     */
    public int getPropertyIDs(int index) {
      return propertyIDs_.get(index);
    }
    /**
     * <code>repeated int32 propertyIDs = 11;</code>
     */
    public Builder setPropertyIDs(
        int index, int value) {
      ensurePropertyIDsIsMutable();
      propertyIDs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 propertyIDs = 11;</code>
     */
    public Builder addPropertyIDs(int value) {
      ensurePropertyIDsIsMutable();
      propertyIDs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 propertyIDs = 11;</code>
     */
    public Builder addAllPropertyIDs(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensurePropertyIDsIsMutable();
      super.addAll(values, propertyIDs_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 propertyIDs = 11;</code>
     */
    public Builder clearPropertyIDs() {
      propertyIDs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }

    // optional string minStarRating = 12;
    private java.lang.Object minStarRating_ = "";
    /**
     * <code>optional string minStarRating = 12;</code>
     */
    public boolean hasMinStarRating() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string minStarRating = 12;</code>
     */
    public java.lang.String getMinStarRating() {
      java.lang.Object ref = minStarRating_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        minStarRating_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string minStarRating = 12;</code>
     */
    public com.google.protobuf.ByteString
        getMinStarRatingBytes() {
      java.lang.Object ref = minStarRating_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        minStarRating_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string minStarRating = 12;</code>
     */
    public Builder setMinStarRating(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      minStarRating_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string minStarRating = 12;</code>
     */
    public Builder clearMinStarRating() {
      bitField0_ = (bitField0_ & ~0x00000800);
      minStarRating_ = getDefaultInstance().getMinStarRating();
      onChanged();
      return this;
    }
    /**
     * <code>optional string minStarRating = 12;</code>
     */
    public Builder setMinStarRatingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      minStarRating_ = value;
      onChanged();
      return this;
    }

    // optional string arrivalDate = 13;
    private java.lang.Object arrivalDate_ = "";
    /**
     * <code>optional string arrivalDate = 13;</code>
     */
    public boolean hasArrivalDate() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string arrivalDate = 13;</code>
     */
    public java.lang.String getArrivalDate() {
      java.lang.Object ref = arrivalDate_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        arrivalDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string arrivalDate = 13;</code>
     */
    public com.google.protobuf.ByteString
        getArrivalDateBytes() {
      java.lang.Object ref = arrivalDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arrivalDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string arrivalDate = 13;</code>
     */
    public Builder setArrivalDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
      arrivalDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string arrivalDate = 13;</code>
     */
    public Builder clearArrivalDate() {
      bitField0_ = (bitField0_ & ~0x00001000);
      arrivalDate_ = getDefaultInstance().getArrivalDate();
      onChanged();
      return this;
    }
    /**
     * <code>optional string arrivalDate = 13;</code>
     */
    public Builder setArrivalDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
      arrivalDate_ = value;
      onChanged();
      return this;
    }

    // optional int32 duration = 14;
    private int duration_ ;
    /**
     * <code>optional int32 duration = 14;</code>
     */
    public boolean hasDuration() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int32 duration = 14;</code>
     */
    public int getDuration() {
      return duration_;
    }
    /**
     * <code>optional int32 duration = 14;</code>
     */
    public Builder setDuration(int value) {
      bitField0_ |= 0x00002000;
      duration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 duration = 14;</code>
     */
    public Builder clearDuration() {
      bitField0_ = (bitField0_ & ~0x00002000);
      duration_ = 0;
      onChanged();
      return this;
    }

    // optional int32 mealBasisID = 15;
    private int mealBasisID_ ;
    /**
     * <code>optional int32 mealBasisID = 15;</code>
     */
    public boolean hasMealBasisID() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int32 mealBasisID = 15;</code>
     */
    public int getMealBasisID() {
      return mealBasisID_;
    }
    /**
     * <code>optional int32 mealBasisID = 15;</code>
     */
    public Builder setMealBasisID(int value) {
      bitField0_ |= 0x00004000;
      mealBasisID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 mealBasisID = 15;</code>
     */
    public Builder clearMealBasisID() {
      bitField0_ = (bitField0_ & ~0x00004000);
      mealBasisID_ = 0;
      onChanged();
      return this;
    }

    // repeated .Jactravel.Monitoring.RoomRequest rooms = 16;
    private java.util.List<com.jactravel.monitoring.RoomRequest> rooms_ =
      java.util.Collections.emptyList();
    private void ensureRoomsIsMutable() {
      if (!((bitField0_ & 0x00008000) == 0x00008000)) {
        rooms_ = new java.util.ArrayList<com.jactravel.monitoring.RoomRequest>(rooms_);
        bitField0_ |= 0x00008000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.jactravel.monitoring.RoomRequest, com.jactravel.monitoring.RoomRequest.Builder, com.jactravel.monitoring.RoomRequestOrBuilder> roomsBuilder_;

    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public java.util.List<com.jactravel.monitoring.RoomRequest> getRoomsList() {
      if (roomsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rooms_);
      } else {
        return roomsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public int getRoomsCount() {
      if (roomsBuilder_ == null) {
        return rooms_.size();
      } else {
        return roomsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public com.jactravel.monitoring.RoomRequest getRooms(int index) {
      if (roomsBuilder_ == null) {
        return rooms_.get(index);
      } else {
        return roomsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public Builder setRooms(
        int index, com.jactravel.monitoring.RoomRequest value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.set(index, value);
        onChanged();
      } else {
        roomsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public Builder setRooms(
        int index, com.jactravel.monitoring.RoomRequest.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.set(index, builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public Builder addRooms(com.jactravel.monitoring.RoomRequest value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.add(value);
        onChanged();
      } else {
        roomsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public Builder addRooms(
        int index, com.jactravel.monitoring.RoomRequest value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.add(index, value);
        onChanged();
      } else {
        roomsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public Builder addRooms(
        com.jactravel.monitoring.RoomRequest.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.add(builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public Builder addRooms(
        int index, com.jactravel.monitoring.RoomRequest.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.add(index, builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public Builder addAllRooms(
        java.lang.Iterable<? extends com.jactravel.monitoring.RoomRequest> values) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        super.addAll(values, rooms_);
        onChanged();
      } else {
        roomsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public Builder clearRooms() {
      if (roomsBuilder_ == null) {
        rooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00008000);
        onChanged();
      } else {
        roomsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public Builder removeRooms(int index) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.remove(index);
        onChanged();
      } else {
        roomsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public com.jactravel.monitoring.RoomRequest.Builder getRoomsBuilder(
        int index) {
      return getRoomsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public com.jactravel.monitoring.RoomRequestOrBuilder getRoomsOrBuilder(
        int index) {
      if (roomsBuilder_ == null) {
        return rooms_.get(index);  } else {
        return roomsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public java.util.List<? extends com.jactravel.monitoring.RoomRequestOrBuilder> 
         getRoomsOrBuilderList() {
      if (roomsBuilder_ != null) {
        return roomsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rooms_);
      }
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public com.jactravel.monitoring.RoomRequest.Builder addRoomsBuilder() {
      return getRoomsFieldBuilder().addBuilder(
          com.jactravel.monitoring.RoomRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public com.jactravel.monitoring.RoomRequest.Builder addRoomsBuilder(
        int index) {
      return getRoomsFieldBuilder().addBuilder(
          index, com.jactravel.monitoring.RoomRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .Jactravel.Monitoring.RoomRequest rooms = 16;</code>
     */
    public java.util.List<com.jactravel.monitoring.RoomRequest.Builder> 
         getRoomsBuilderList() {
      return getRoomsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.jactravel.monitoring.RoomRequest, com.jactravel.monitoring.RoomRequest.Builder, com.jactravel.monitoring.RoomRequestOrBuilder> 
        getRoomsFieldBuilder() {
      if (roomsBuilder_ == null) {
        roomsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.jactravel.monitoring.RoomRequest, com.jactravel.monitoring.RoomRequest.Builder, com.jactravel.monitoring.RoomRequestOrBuilder>(
                rooms_,
                ((bitField0_ & 0x00008000) == 0x00008000),
                getParentForChildren(),
                isClean());
        rooms_ = null;
      }
      return roomsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Jactravel.Monitoring.SearchRequestInfo)
  }

  static {
    defaultInstance = new SearchRequestInfo(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Jactravel.Monitoring.SearchRequestInfo)
}

