// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchReport.proto

package com.jactravel.monitoring;

public final class SearchReportProto {
  private SearchReportProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Jactravel_Monitoring_SearchReport_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Jactravel_Monitoring_SearchReport_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Jactravel_Monitoring_SearchRequestInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Jactravel_Monitoring_SearchRequestInfo_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Jactravel_Monitoring_SearchResponseInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Jactravel_Monitoring_SearchResponseInfo_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Jactravel_Monitoring_RoomRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Jactravel_Monitoring_RoomRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SearchReport.proto\022\024Jactravel.Monitori" +
      "ng\"\255\001\n\014SearchReport\022\021\n\tqueryUUID\030\001 \001(\t\022\014" +
      "\n\004host\030\002 \001(\t\022<\n\013requestInfo\030\004 \001(\0132\'.Jact" +
      "ravel.Monitoring.SearchRequestInfo\022>\n\014re" +
      "sponseInfo\030\005 \001(\0132(.Jactravel.Monitoring." +
      "SearchResponseInfo\"\261\003\n\021SearchRequestInfo" +
      "\022\031\n\021startUtcTimestamp\030\001 \001(\t\022\027\n\017endUtcTim" +
      "estamp\030\002 \001(\t\022\017\n\007tradeID\030\003 \001(\005\022\017\n\007brandID" +
      "\030\004 \001(\005\022\026\n\016salesChannelID\030\005 \001(\005\0226\n\016search" +
      "GeoLevel\030\006 \001(\0162\036.Jactravel.Monitoring.Ge",
      "oLevel\022\023\n\013geoLevel1ID\030\007 \001(\005\022\023\n\013geoLevel2" +
      "ID\030\010 \001(\005\022\024\n\014geoLevel3IDs\030\t \003(\005\022\034\n\024proper" +
      "tyReferenceIDs\030\n \003(\005\022\023\n\013propertyIDs\030\013 \003(" +
      "\005\022\025\n\rminStarRating\030\014 \001(\t\022\023\n\013arrivalDate\030" +
      "\r \001(\t\022\020\n\010duration\030\016 \001(\005\022\023\n\013mealBasisID\030\017" +
      " \001(\005\0220\n\005rooms\030\020 \003(\0132!.Jactravel.Monitori" +
      "ng.RoomRequest\"\277\001\n\022SearchResponseInfo\022\036\n" +
      "\026propertyReferenceCount\030\001 \001(\005\022\025\n\rpropert" +
      "yCount\030\002 \001(\005\022\027\n\017pricedRoomCount\030\003 \001(\005\022\031\n" +
      "\021suppliersSearched\030\004 \003(\t\022\017\n\007success\030\005 \001(",
      "\t\022\024\n\014errorMessage\030\006 \001(\t\022\027\n\017errorStackTra" +
      "ce\030\007 \001(\t\"B\n\013RoomRequest\022\016\n\006adults\030\001 \001(\005\022" +
      "\020\n\010children\030\002 \001(\005\022\021\n\tchildAges\030\003 \003(\005*k\n\010" +
      "GeoLevel\022\023\n\017UnknownGeoLevel\020\000\022\013\n\007Country" +
      "\020\001\022\n\n\006Region\020\002\022\n\n\006Resort\020\003\022\025\n\021PropertyRe" +
      "ference\020\004\022\016\n\nPropertyID\020\005B/\n\030com.jactrav" +
      "el.monitoringB\021SearchReportProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Jactravel_Monitoring_SearchReport_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Jactravel_Monitoring_SearchReport_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Jactravel_Monitoring_SearchReport_descriptor,
              new java.lang.String[] { "QueryUUID", "Host", "RequestInfo", "ResponseInfo", });
          internal_static_Jactravel_Monitoring_SearchRequestInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Jactravel_Monitoring_SearchRequestInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Jactravel_Monitoring_SearchRequestInfo_descriptor,
              new java.lang.String[] { "StartUtcTimestamp", "EndUtcTimestamp", "TradeID", "BrandID", "SalesChannelID", "SearchGeoLevel", "GeoLevel1ID", "GeoLevel2ID", "GeoLevel3IDs", "PropertyReferenceIDs", "PropertyIDs", "MinStarRating", "ArrivalDate", "Duration", "MealBasisID", "Rooms", });
          internal_static_Jactravel_Monitoring_SearchResponseInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Jactravel_Monitoring_SearchResponseInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Jactravel_Monitoring_SearchResponseInfo_descriptor,
              new java.lang.String[] { "PropertyReferenceCount", "PropertyCount", "PricedRoomCount", "SuppliersSearched", "Success", "ErrorMessage", "ErrorStackTrace", });
          internal_static_Jactravel_Monitoring_RoomRequest_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Jactravel_Monitoring_RoomRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Jactravel_Monitoring_RoomRequest_descriptor,
              new java.lang.String[] { "Adults", "Children", "ChildAges", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
