// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupplierSearchRequest.proto

package com.jactravel.monitoring;

public interface SupplierSearchRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string queryUUID = 1;
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  boolean hasQueryUUID();
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  java.lang.String getQueryUUID();
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  com.google.protobuf.ByteString
      getQueryUUIDBytes();

  // optional string host = 2;
  /**
   * <code>optional string host = 2;</code>
   */
  boolean hasHost();
  /**
   * <code>optional string host = 2;</code>
   */
  java.lang.String getHost();
  /**
   * <code>optional string host = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  // optional string source = 3;
  /**
   * <code>optional string source = 3;</code>
   */
  boolean hasSource();
  /**
   * <code>optional string source = 3;</code>
   */
  java.lang.String getSource();
  /**
   * <code>optional string source = 3;</code>
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  // optional string startUtcTimestamp = 4;
  /**
   * <code>optional string startUtcTimestamp = 4;</code>
   */
  boolean hasStartUtcTimestamp();
  /**
   * <code>optional string startUtcTimestamp = 4;</code>
   */
  java.lang.String getStartUtcTimestamp();
  /**
   * <code>optional string startUtcTimestamp = 4;</code>
   */
  com.google.protobuf.ByteString
      getStartUtcTimestampBytes();

  // optional string endUtcTimestamp = 5;
  /**
   * <code>optional string endUtcTimestamp = 5;</code>
   */
  boolean hasEndUtcTimestamp();
  /**
   * <code>optional string endUtcTimestamp = 5;</code>
   */
  java.lang.String getEndUtcTimestamp();
  /**
   * <code>optional string endUtcTimestamp = 5;</code>
   */
  com.google.protobuf.ByteString
      getEndUtcTimestampBytes();

  // optional int32 timeout = 6;
  /**
   * <code>optional int32 timeout = 6;</code>
   */
  boolean hasTimeout();
  /**
   * <code>optional int32 timeout = 6;</code>
   */
  int getTimeout();

  // optional int32 propertyCount = 7;
  /**
   * <code>optional int32 propertyCount = 7;</code>
   */
  boolean hasPropertyCount();
  /**
   * <code>optional int32 propertyCount = 7;</code>
   */
  int getPropertyCount();

  // optional string success = 8;
  /**
   * <code>optional string success = 8;</code>
   */
  boolean hasSuccess();
  /**
   * <code>optional string success = 8;</code>
   */
  java.lang.String getSuccess();
  /**
   * <code>optional string success = 8;</code>
   */
  com.google.protobuf.ByteString
      getSuccessBytes();

  // optional string errorMessage = 9;
  /**
   * <code>optional string errorMessage = 9;</code>
   */
  boolean hasErrorMessage();
  /**
   * <code>optional string errorMessage = 9;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>optional string errorMessage = 9;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  // optional string errorStackTrace = 10;
  /**
   * <code>optional string errorStackTrace = 10;</code>
   */
  boolean hasErrorStackTrace();
  /**
   * <code>optional string errorStackTrace = 10;</code>
   */
  java.lang.String getErrorStackTrace();
  /**
   * <code>optional string errorStackTrace = 10;</code>
   */
  com.google.protobuf.ByteString
      getErrorStackTraceBytes();

  // optional string requestXML = 11;
  /**
   * <code>optional string requestXML = 11;</code>
   */
  boolean hasRequestXML();
  /**
   * <code>optional string requestXML = 11;</code>
   */
  java.lang.String getRequestXML();
  /**
   * <code>optional string requestXML = 11;</code>
   */
  com.google.protobuf.ByteString
      getRequestXMLBytes();

  // optional string responseXML = 12;
  /**
   * <code>optional string responseXML = 12;</code>
   */
  boolean hasResponseXML();
  /**
   * <code>optional string responseXML = 12;</code>
   */
  java.lang.String getResponseXML();
  /**
   * <code>optional string responseXML = 12;</code>
   */
  com.google.protobuf.ByteString
      getResponseXMLBytes();

  // optional int32 requestCount = 13;
  /**
   * <code>optional int32 requestCount = 13;</code>
   */
  boolean hasRequestCount();
  /**
   * <code>optional int32 requestCount = 13;</code>
   */
  int getRequestCount();
}
