// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupplierBookRequest.proto

package com.jactravel.monitoring;

public final class SupplierBookRequestProto {
  private SupplierBookRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Jactravel_Monitoring_SupplierBookRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Jactravel_Monitoring_SupplierBookRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031SupplierBookRequest.proto\022\024Jactravel.M" +
      "onitoring\"\342\001\n\023SupplierBookRequest\022\021\n\tque" +
      "ryUUID\030\001 \001(\t\022\014\n\004host\030\002 \001(\t\022\016\n\006source\030\003 \001" +
      "(\t\022\031\n\021startUtcTimestamp\030\004 \001(\t\022\027\n\017endUtcT" +
      "imestamp\030\005 \001(\t\022\017\n\007timeout\030\006 \001(\005\022\025\n\rprope" +
      "rtyCount\030\007 \001(\005\022\017\n\007success\030\010 \001(\t\022\024\n\014error" +
      "Message\030\t \001(\t\022\027\n\017errorStackTrace\030\n \001(\tB6" +
      "\n\030com.jactravel.monitoringB\030SupplierBook" +
      "RequestProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Jactravel_Monitoring_SupplierBookRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Jactravel_Monitoring_SupplierBookRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Jactravel_Monitoring_SupplierBookRequest_descriptor,
              new java.lang.String[] { "QueryUUID", "Host", "Source", "StartUtcTimestamp", "EndUtcTimestamp", "Timeout", "PropertyCount", "Success", "ErrorMessage", "ErrorStackTrace", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
