// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupplierPreBookRequest.proto

package com.jactravel.monitoring;

/**
 * Protobuf type {@code Jactravel.Monitoring.SupplierPreBookRequest}
 */
public  final class SupplierPreBookRequest extends
    com.google.protobuf.GeneratedMessage
    implements SupplierPreBookRequestOrBuilder {
  // Use SupplierPreBookRequest.newBuilder() to construct.
  private SupplierPreBookRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private SupplierPreBookRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final SupplierPreBookRequest defaultInstance;
  public static SupplierPreBookRequest getDefaultInstance() {
    return defaultInstance;
  }

  public SupplierPreBookRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private SupplierPreBookRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            queryUUID_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            host_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            source_ = input.readBytes();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            startUtcTimestamp_ = input.readBytes();
            break;
          }
          case 42: {
            bitField0_ |= 0x00000010;
            endUtcTimestamp_ = input.readBytes();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            timeout_ = input.readInt32();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            propertyCount_ = input.readInt32();
            break;
          }
          case 66: {
            bitField0_ |= 0x00000080;
            success_ = input.readBytes();
            break;
          }
          case 74: {
            bitField0_ |= 0x00000100;
            errorMessage_ = input.readBytes();
            break;
          }
          case 82: {
            bitField0_ |= 0x00000200;
            errorStackTrace_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jactravel.monitoring.SupplierPreBookRequestProto.internal_static_Jactravel_Monitoring_SupplierPreBookRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jactravel.monitoring.SupplierPreBookRequestProto.internal_static_Jactravel_Monitoring_SupplierPreBookRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jactravel.monitoring.SupplierPreBookRequest.class, com.jactravel.monitoring.SupplierPreBookRequest.Builder.class);
  }

  public static com.google.protobuf.Parser<SupplierPreBookRequest> PARSER =
      new com.google.protobuf.AbstractParser<SupplierPreBookRequest>() {
    public SupplierPreBookRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SupplierPreBookRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<SupplierPreBookRequest> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional string queryUUID = 1;
  public static final int QUERYUUID_FIELD_NUMBER = 1;
  private java.lang.Object queryUUID_;
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  public boolean hasQueryUUID() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  public java.lang.String getQueryUUID() {
    java.lang.Object ref = queryUUID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        queryUUID_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string queryUUID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getQueryUUIDBytes() {
    java.lang.Object ref = queryUUID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      queryUUID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string host = 2;
  public static final int HOST_FIELD_NUMBER = 2;
  private java.lang.Object host_;
  /**
   * <code>optional string host = 2;</code>
   */
  public boolean hasHost() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string host = 2;</code>
   */
  public java.lang.String getHost() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        host_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string host = 2;</code>
   */
  public com.google.protobuf.ByteString
      getHostBytes() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      host_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string source = 3;
  public static final int SOURCE_FIELD_NUMBER = 3;
  private java.lang.Object source_;
  /**
   * <code>optional string source = 3;</code>
   */
  public boolean hasSource() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string source = 3;</code>
   */
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        source_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string source = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string startUtcTimestamp = 4;
  public static final int STARTUTCTIMESTAMP_FIELD_NUMBER = 4;
  private java.lang.Object startUtcTimestamp_;
  /**
   * <code>optional string startUtcTimestamp = 4;</code>
   */
  public boolean hasStartUtcTimestamp() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string startUtcTimestamp = 4;</code>
   */
  public java.lang.String getStartUtcTimestamp() {
    java.lang.Object ref = startUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        startUtcTimestamp_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string startUtcTimestamp = 4;</code>
   */
  public com.google.protobuf.ByteString
      getStartUtcTimestampBytes() {
    java.lang.Object ref = startUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startUtcTimestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string endUtcTimestamp = 5;
  public static final int ENDUTCTIMESTAMP_FIELD_NUMBER = 5;
  private java.lang.Object endUtcTimestamp_;
  /**
   * <code>optional string endUtcTimestamp = 5;</code>
   */
  public boolean hasEndUtcTimestamp() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string endUtcTimestamp = 5;</code>
   */
  public java.lang.String getEndUtcTimestamp() {
    java.lang.Object ref = endUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        endUtcTimestamp_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string endUtcTimestamp = 5;</code>
   */
  public com.google.protobuf.ByteString
      getEndUtcTimestampBytes() {
    java.lang.Object ref = endUtcTimestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endUtcTimestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int32 timeout = 6;
  public static final int TIMEOUT_FIELD_NUMBER = 6;
  private int timeout_;
  /**
   * <code>optional int32 timeout = 6;</code>
   */
  public boolean hasTimeout() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional int32 timeout = 6;</code>
   */
  public int getTimeout() {
    return timeout_;
  }

  // optional int32 propertyCount = 7;
  public static final int PROPERTYCOUNT_FIELD_NUMBER = 7;
  private int propertyCount_;
  /**
   * <code>optional int32 propertyCount = 7;</code>
   */
  public boolean hasPropertyCount() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional int32 propertyCount = 7;</code>
   */
  public int getPropertyCount() {
    return propertyCount_;
  }

  // optional string success = 8;
  public static final int SUCCESS_FIELD_NUMBER = 8;
  private java.lang.Object success_;
  /**
   * <code>optional string success = 8;</code>
   */
  public boolean hasSuccess() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional string success = 8;</code>
   */
  public java.lang.String getSuccess() {
    java.lang.Object ref = success_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        success_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string success = 8;</code>
   */
  public com.google.protobuf.ByteString
      getSuccessBytes() {
    java.lang.Object ref = success_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      success_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string errorMessage = 9;
  public static final int ERRORMESSAGE_FIELD_NUMBER = 9;
  private java.lang.Object errorMessage_;
  /**
   * <code>optional string errorMessage = 9;</code>
   */
  public boolean hasErrorMessage() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional string errorMessage = 9;</code>
   */
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        errorMessage_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string errorMessage = 9;</code>
   */
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string errorStackTrace = 10;
  public static final int ERRORSTACKTRACE_FIELD_NUMBER = 10;
  private java.lang.Object errorStackTrace_;
  /**
   * <code>optional string errorStackTrace = 10;</code>
   */
  public boolean hasErrorStackTrace() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional string errorStackTrace = 10;</code>
   */
  public java.lang.String getErrorStackTrace() {
    java.lang.Object ref = errorStackTrace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        errorStackTrace_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string errorStackTrace = 10;</code>
   */
  public com.google.protobuf.ByteString
      getErrorStackTraceBytes() {
    java.lang.Object ref = errorStackTrace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorStackTrace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    queryUUID_ = "";
    host_ = "";
    source_ = "";
    startUtcTimestamp_ = "";
    endUtcTimestamp_ = "";
    timeout_ = 0;
    propertyCount_ = 0;
    success_ = "";
    errorMessage_ = "";
    errorStackTrace_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getQueryUUIDBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getHostBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getSourceBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getStartUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getEndUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeInt32(6, timeout_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeInt32(7, propertyCount_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeBytes(8, getSuccessBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeBytes(9, getErrorMessageBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeBytes(10, getErrorStackTraceBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getQueryUUIDBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getHostBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getSourceBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getStartUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getEndUtcTimestampBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, timeout_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, propertyCount_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, getSuccessBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, getErrorMessageBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, getErrorStackTraceBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.jactravel.monitoring.SupplierPreBookRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jactravel.monitoring.SupplierPreBookRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jactravel.monitoring.SupplierPreBookRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jactravel.monitoring.SupplierPreBookRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jactravel.monitoring.SupplierPreBookRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.jactravel.monitoring.SupplierPreBookRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.jactravel.monitoring.SupplierPreBookRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.jactravel.monitoring.SupplierPreBookRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.jactravel.monitoring.SupplierPreBookRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.jactravel.monitoring.SupplierPreBookRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.jactravel.monitoring.SupplierPreBookRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Jactravel.Monitoring.SupplierPreBookRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.jactravel.monitoring.SupplierPreBookRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jactravel.monitoring.SupplierPreBookRequestProto.internal_static_Jactravel_Monitoring_SupplierPreBookRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jactravel.monitoring.SupplierPreBookRequestProto.internal_static_Jactravel_Monitoring_SupplierPreBookRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jactravel.monitoring.SupplierPreBookRequest.class, com.jactravel.monitoring.SupplierPreBookRequest.Builder.class);
    }

    // Construct using com.jactravel.monitoring.SupplierPreBookRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      queryUUID_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      host_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      source_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      startUtcTimestamp_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      endUtcTimestamp_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      timeout_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      propertyCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000040);
      success_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      errorMessage_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      errorStackTrace_ = "";
      bitField0_ = (bitField0_ & ~0x00000200);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jactravel.monitoring.SupplierPreBookRequestProto.internal_static_Jactravel_Monitoring_SupplierPreBookRequest_descriptor;
    }

    public com.jactravel.monitoring.SupplierPreBookRequest getDefaultInstanceForType() {
      return com.jactravel.monitoring.SupplierPreBookRequest.getDefaultInstance();
    }

    public com.jactravel.monitoring.SupplierPreBookRequest build() {
      com.jactravel.monitoring.SupplierPreBookRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jactravel.monitoring.SupplierPreBookRequest buildPartial() {
      com.jactravel.monitoring.SupplierPreBookRequest result = new com.jactravel.monitoring.SupplierPreBookRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.queryUUID_ = queryUUID_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.host_ = host_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.source_ = source_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.startUtcTimestamp_ = startUtcTimestamp_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.endUtcTimestamp_ = endUtcTimestamp_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.timeout_ = timeout_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.propertyCount_ = propertyCount_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.success_ = success_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.errorMessage_ = errorMessage_;
      if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
        to_bitField0_ |= 0x00000200;
      }
      result.errorStackTrace_ = errorStackTrace_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jactravel.monitoring.SupplierPreBookRequest) {
        return mergeFrom((com.jactravel.monitoring.SupplierPreBookRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jactravel.monitoring.SupplierPreBookRequest other) {
      if (other == com.jactravel.monitoring.SupplierPreBookRequest.getDefaultInstance()) return this;
      if (other.hasQueryUUID()) {
        bitField0_ |= 0x00000001;
        queryUUID_ = other.queryUUID_;
        onChanged();
      }
      if (other.hasHost()) {
        bitField0_ |= 0x00000002;
        host_ = other.host_;
        onChanged();
      }
      if (other.hasSource()) {
        bitField0_ |= 0x00000004;
        source_ = other.source_;
        onChanged();
      }
      if (other.hasStartUtcTimestamp()) {
        bitField0_ |= 0x00000008;
        startUtcTimestamp_ = other.startUtcTimestamp_;
        onChanged();
      }
      if (other.hasEndUtcTimestamp()) {
        bitField0_ |= 0x00000010;
        endUtcTimestamp_ = other.endUtcTimestamp_;
        onChanged();
      }
      if (other.hasTimeout()) {
        setTimeout(other.getTimeout());
      }
      if (other.hasPropertyCount()) {
        setPropertyCount(other.getPropertyCount());
      }
      if (other.hasSuccess()) {
        bitField0_ |= 0x00000080;
        success_ = other.success_;
        onChanged();
      }
      if (other.hasErrorMessage()) {
        bitField0_ |= 0x00000100;
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      if (other.hasErrorStackTrace()) {
        bitField0_ |= 0x00000200;
        errorStackTrace_ = other.errorStackTrace_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jactravel.monitoring.SupplierPreBookRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jactravel.monitoring.SupplierPreBookRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string queryUUID = 1;
    private java.lang.Object queryUUID_ = "";
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public boolean hasQueryUUID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public java.lang.String getQueryUUID() {
      java.lang.Object ref = queryUUID_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        queryUUID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryUUIDBytes() {
      java.lang.Object ref = queryUUID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queryUUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public Builder setQueryUUID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      queryUUID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public Builder clearQueryUUID() {
      bitField0_ = (bitField0_ & ~0x00000001);
      queryUUID_ = getDefaultInstance().getQueryUUID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string queryUUID = 1;</code>
     */
    public Builder setQueryUUIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      queryUUID_ = value;
      onChanged();
      return this;
    }

    // optional string host = 2;
    private java.lang.Object host_ = "";
    /**
     * <code>optional string host = 2;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string host = 2;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        host_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string host = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string host = 2;</code>
     */
    public Builder setHost(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      host_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string host = 2;</code>
     */
    public Builder clearHost() {
      bitField0_ = (bitField0_ & ~0x00000002);
      host_ = getDefaultInstance().getHost();
      onChanged();
      return this;
    }
    /**
     * <code>optional string host = 2;</code>
     */
    public Builder setHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      host_ = value;
      onChanged();
      return this;
    }

    // optional string source = 3;
    private java.lang.Object source_ = "";
    /**
     * <code>optional string source = 3;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string source = 3;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string source = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string source = 3;</code>
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string source = 3;</code>
     */
    public Builder clearSource() {
      bitField0_ = (bitField0_ & ~0x00000004);
      source_ = getDefaultInstance().getSource();
      onChanged();
      return this;
    }
    /**
     * <code>optional string source = 3;</code>
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      source_ = value;
      onChanged();
      return this;
    }

    // optional string startUtcTimestamp = 4;
    private java.lang.Object startUtcTimestamp_ = "";
    /**
     * <code>optional string startUtcTimestamp = 4;</code>
     */
    public boolean hasStartUtcTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string startUtcTimestamp = 4;</code>
     */
    public java.lang.String getStartUtcTimestamp() {
      java.lang.Object ref = startUtcTimestamp_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        startUtcTimestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string startUtcTimestamp = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStartUtcTimestampBytes() {
      java.lang.Object ref = startUtcTimestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startUtcTimestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string startUtcTimestamp = 4;</code>
     */
    public Builder setStartUtcTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      startUtcTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string startUtcTimestamp = 4;</code>
     */
    public Builder clearStartUtcTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      startUtcTimestamp_ = getDefaultInstance().getStartUtcTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string startUtcTimestamp = 4;</code>
     */
    public Builder setStartUtcTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      startUtcTimestamp_ = value;
      onChanged();
      return this;
    }

    // optional string endUtcTimestamp = 5;
    private java.lang.Object endUtcTimestamp_ = "";
    /**
     * <code>optional string endUtcTimestamp = 5;</code>
     */
    public boolean hasEndUtcTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string endUtcTimestamp = 5;</code>
     */
    public java.lang.String getEndUtcTimestamp() {
      java.lang.Object ref = endUtcTimestamp_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        endUtcTimestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string endUtcTimestamp = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEndUtcTimestampBytes() {
      java.lang.Object ref = endUtcTimestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endUtcTimestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string endUtcTimestamp = 5;</code>
     */
    public Builder setEndUtcTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      endUtcTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string endUtcTimestamp = 5;</code>
     */
    public Builder clearEndUtcTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000010);
      endUtcTimestamp_ = getDefaultInstance().getEndUtcTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string endUtcTimestamp = 5;</code>
     */
    public Builder setEndUtcTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      endUtcTimestamp_ = value;
      onChanged();
      return this;
    }

    // optional int32 timeout = 6;
    private int timeout_ ;
    /**
     * <code>optional int32 timeout = 6;</code>
     */
    public boolean hasTimeout() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 timeout = 6;</code>
     */
    public int getTimeout() {
      return timeout_;
    }
    /**
     * <code>optional int32 timeout = 6;</code>
     */
    public Builder setTimeout(int value) {
      bitField0_ |= 0x00000020;
      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 timeout = 6;</code>
     */
    public Builder clearTimeout() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timeout_ = 0;
      onChanged();
      return this;
    }

    // optional int32 propertyCount = 7;
    private int propertyCount_ ;
    /**
     * <code>optional int32 propertyCount = 7;</code>
     */
    public boolean hasPropertyCount() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 propertyCount = 7;</code>
     */
    public int getPropertyCount() {
      return propertyCount_;
    }
    /**
     * <code>optional int32 propertyCount = 7;</code>
     */
    public Builder setPropertyCount(int value) {
      bitField0_ |= 0x00000040;
      propertyCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 propertyCount = 7;</code>
     */
    public Builder clearPropertyCount() {
      bitField0_ = (bitField0_ & ~0x00000040);
      propertyCount_ = 0;
      onChanged();
      return this;
    }

    // optional string success = 8;
    private java.lang.Object success_ = "";
    /**
     * <code>optional string success = 8;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string success = 8;</code>
     */
    public java.lang.String getSuccess() {
      java.lang.Object ref = success_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        success_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string success = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSuccessBytes() {
      java.lang.Object ref = success_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        success_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string success = 8;</code>
     */
    public Builder setSuccess(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string success = 8;</code>
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000080);
      success_ = getDefaultInstance().getSuccess();
      onChanged();
      return this;
    }
    /**
     * <code>optional string success = 8;</code>
     */
    public Builder setSuccessBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      success_ = value;
      onChanged();
      return this;
    }

    // optional string errorMessage = 9;
    private java.lang.Object errorMessage_ = "";
    /**
     * <code>optional string errorMessage = 9;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string errorMessage = 9;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string errorMessage = 9;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string errorMessage = 9;</code>
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorMessage = 9;</code>
     */
    public Builder clearErrorMessage() {
      bitField0_ = (bitField0_ & ~0x00000100);
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorMessage = 9;</code>
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      errorMessage_ = value;
      onChanged();
      return this;
    }

    // optional string errorStackTrace = 10;
    private java.lang.Object errorStackTrace_ = "";
    /**
     * <code>optional string errorStackTrace = 10;</code>
     */
    public boolean hasErrorStackTrace() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string errorStackTrace = 10;</code>
     */
    public java.lang.String getErrorStackTrace() {
      java.lang.Object ref = errorStackTrace_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        errorStackTrace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string errorStackTrace = 10;</code>
     */
    public com.google.protobuf.ByteString
        getErrorStackTraceBytes() {
      java.lang.Object ref = errorStackTrace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorStackTrace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string errorStackTrace = 10;</code>
     */
    public Builder setErrorStackTrace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      errorStackTrace_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorStackTrace = 10;</code>
     */
    public Builder clearErrorStackTrace() {
      bitField0_ = (bitField0_ & ~0x00000200);
      errorStackTrace_ = getDefaultInstance().getErrorStackTrace();
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorStackTrace = 10;</code>
     */
    public Builder setErrorStackTraceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      errorStackTrace_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Jactravel.Monitoring.SupplierPreBookRequest)
  }

  static {
    defaultInstance = new SupplierPreBookRequest(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Jactravel.Monitoring.SupplierPreBookRequest)
}

